### ISSUE TITLE
Splunk HEC sends 400 and logs error: "Got unexpected null element while expecting event's raw text"

### ISSUE THREAD

**Issue by vinzent** [signalfx/splunk-otel-collector-chart#1002]
We have upgraded from Splunk Otel Chart 0.79.0 to 0.86.1. We've been using `logsEngine: otel` already with 0.79.0. We only collect logs. Splunk server-side is 9.0.5. Distribution is OpenShift 4.12. 

We are using the metric `otelcol_exporter_send_failed_log_records` to detect issues with sending to Splunk.  Since the upgrade, we now get somewhat regularly alerts on this. 

We then see splunk-otel-collector logs like:

```
<...> Exporting failed. The error is not retryable <...> 
{\\\"text\\\":\\\"Invalid data format\\\",\\\"code\\\":6,\\\"invalid-event-number\\\":0}\"", "dropped_items": 6}
```

The splunkd.log shows an ERROR containing: 

```
<...> parsing_err="Got unexpected null element while expecting event's raw text, totalRequestSize=6705"
```

Seems like the splunk-otel-collector somehow constructs an invalid HEC event.

---

Full splunk otel collector log:

```
2023-11-01T11:16:03.860Z        error   exporterhelper/retry_sender.go:145      Exporting failed. The error is not retryable. Dropping data.    {"kind": "exporter", "data_type": "logs", "name": "splunk_hec/platform_logs", "error": "Permanent error: \"HTTP/1.1 400 Bad Request\\r\\nContent-Length: 64\\r\\nConnection:
Keep-Alive\\r\\nContent-Type: application/json; charset=UTF-8\\r\\nDate: Wed, 01 Nov 2023 11:16:03 GMT\\r\\nServer: Splunkd\\r\\nVary: Authorization\\r\\nX-Content-Type-Options: nosniff\\r\\nX-Frame-Options: SAMEORIGIN\\r\\n\\r\\n{\\\"text\\\":\\\"Invalid data format\\\",\\\"code\\\":6,\\\"invalid-event-number\\\":0}\"", "dropped_items": 6}
go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send
        [go.opentelemetry.io/collector/exporter@v0.86.0/exporterhelper/retry_sender.go:145](mailto:go.opentelemetry.io/collector/exporter@v0.86.0/exporterhelper/retry_sender.go:145)
go.opentelemetry.io/collector/exporter/exporterhelper.(*logsExporterWithObservability).send
        [go.opentelemetry.io/collector/exporter@v0.86.0/exporterhelper/logs.go:176](mailto:go.opentelemetry.io/collector/exporter@v0.86.0/exporterhelper/logs.go:176)
go.opentelemetry.io/collector/exporter/exporterhelper.(*queueSender).start.func1
        [go.opentelemetry.io/collector/exporter@v0.86.0/exporterhelper/queue_sender.go:124](mailto:go.opentelemetry.io/collector/exporter@v0.86.0/exporterhelper/queue_sender.go:124)
go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue).Start.func1
        [go.opentelemetry.io/collector/exporter@v0.86.0/exporterhelper/internal/bounded_memory_queue.go:52](mailto:go.opentelemetry.io/collector/exporter@v0.86.0/exporterhelper/internal/bounded_memory_queue.go:52)
```

The corresponding Splunkd.log:

```
11-01-2023 12:16:03.859 +0100 ERROR HttpInputDataHandler [13954 HttpDedicatedIoThread-5] - Failed processing http input, token name=k8scluster, channel=n/a, source_IP=10.10.10.30, reply=6, events_processed=0, http_input_body_size=6705, parsing_err="Got unexpected null element while expecting event's raw text, totalRequestSize=6705"
```

**Comment by vinzent** [comment]
Manually crafting and sending a HEC message like:

```
{
  "host": "x", 
  "source": "/var/log/test.log", 
  "sourcetype": "text", 
  "index": "openshift", 
  "event": null 
}
```

triggers the `Got unexpected null element while expecting event's raw text` error on the splunk side.

Sending completly without the `event` property, the HEC response contains `event field is required`.

Im quite sure, the Splunk Otel collector sends `event: null`.

**Comment by matthewmodestino** [comment]
The default logging pipeline does include config to try and avoid "empty lines".

```
        - field: attributes.log
          id: handle_empty_log
          if: attributes.log == nil
          type: add
          value: ""
```

Do you have any log pipeline customizations?

Might be worth flipping on debug or trace on otel or splunk side to identify what the actual invalid event is..

**Comment by vinzent** [comment]
I only get the alert on control-plane nodes.  And it's always only one node out of three. I presume, the one that has the most load. The different to application nodes is, that there are additional audit logs configured for these control-plane machines. The additional (audit) logfiles are the only "customization" I have. 

I thought about adding a print to https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/b716a4d89acd497cb1ed044b941c49a7897b72bb/exporter/splunkhecexporter/logdata_to_splunk.go#L86 where `lr.Body().AsRaw()` is nil to get the context of the event. But I failed to understand/learn how to compile the binary.

**Comment by matthewmodestino** [comment]
Hmm, u might be on to something there. I'll need to check what the `extraFileLogs` pipeline renders as it may not have the same safeguards built in as the default container pipeline. I'll double check.

In the meantime you can turn on debug logging and should be able to capture the smoking gun.


```
agent:
  config:
    exporters:
      logging:
        loglevel: debug
    service:
      pipelines:
        logs:
          exporters:
            - splunk_hec/platform_logs
            - logging



```

**Comment by vinzent** [comment]
I think there is no "handle_empty_log" thing for extraFileLogs. but I haven't found empty lines in the audit logs.  i will configure an extra file to test manually.

the issue with the debug is: it logs really much and the issue only occurs randomly. sometimes it takes more than a day until it happens again. pod logs get rotated.  I will try anyways.

**Comment by matthewmodestino** [comment]
Yeah, wish there was a better way..might open an enhancement to log the payload to console when a 4xx is received..would help..

Yeah i looked at the extrafile log pipelines and they are very simple and dont have the handle empty logs operator.

I would probably add it, regardless. Another good enhancement request, imo. 

It may not actually be an empty log, but could be a whitespace line or even control chars etc

Getting closer...

**Comment by vinzent** [comment]
I enabled the debug logging now. 

btw. 

> This exporter is being deprecated in favour of the [debug exporter](https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/debugexporter/README.md). It will be removed in September 2024.

https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/loggingexporter/README.md

**Comment by matthewmodestino** [comment]
yeah that was just the example i had on hand. we do ship that exporter now if you want to try it instead:

https://github.com/open-telemetry/opentelemetry-collector/tree/main/exporter/debugexporter

also, you can disable collection of agent logs while you have debug on if you want. or even just update only that particular daemonset on the node in question. 

https://github.com/signalfx/splunk-otel-collector-chart/blob/62e5f2246597f2031bb7b1cc2fe654d20136c322/helm-charts/splunk-otel-collector/values.yaml#L555

**Comment by atoulme** [comment]
Filing https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/29551 and taking a look.

**Comment by vinzent** [comment]
We have upgraded to OpenShift 4.12 to 4.13 (k8s from 1.25.11 to 1.26.9) on 2023-11-15. While the platform-upgrade was in progress, the alert could be observed on different nodes, not only on control-plane nodes. Unfortunately i was not able to gather the debug logs.  

But: there was no alert anymore after 2023-11-15.

**Comment by atoulme** [comment]
Closing as done - we have a fix upstream so no nil body is possible. If you see issues again, please open a support case.
