### ISSUE TITLE
Include namespace in metadata 

### ISSUE THREAD

**Issue by dmitchsplunk** [signalfx/splunk-otel-collector-chart#1011]
When using helm to generate templates with the splunk-otel-collector chart: 

`helm template --namespace mynamespace --values values.yaml --output-dir <rendered_manifests_dir> --generate-name splunk-otel-collector-chart/splunk-otel-collector`

The desired namespace is not added to the metadata section of the resulting templates.   For example, [daemonset.yaml](https://github.com/signalfx/splunk-otel-collector-chart/blob/main/helm-charts/splunk-otel-collector/templates/daemonset.yaml) does not include the namespace. 

The request is to add the namespace to the generated templates, similar to how it's added in the upstream collector chart.  See [daemonset.yaml](https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-collector/templates/daemonset.yaml) as an example: 

```
metadata:
  name: {{ include "opentelemetry-collector.fullname" . }}-agent
  namespace: {{ template "opentelemetry-collector.namespace" . }}
```
  
The workaround is to add the namespace manually to the rendered manifests, or add the "--namespace" argument when applying the manifests with kubectl.

**Comment by atoulme** [comment]
We will be working towards implementing this support. Please follow up internally for updates. Thanks!
