### ISSUE TITLE
hostname is showing up as unknown

### ISSUE THREAD

**Issue by xxPhuNguyenxx** [signalfx/splunk-otel-collector-chart#1035]
why are some sourcetypes showing up as "unknown"? Splunk connect for Kubernetes never had hosts that were showing up as "unknown"

Here's our values.yaml
agent:
  config:
    processors:
      filter/exclude_all_telemetry_data_from_namespace:
        logs:
          exclude:
            match_type: regexp
            resource_attributes:
            - key: k8s.namespace.name
              value: ^(datadog)$
        metrics:
          exclude:
            match_type: regexp
            resource_attributes:
            - key: k8s.namespace.name
              value: ^(datadog)$
        traces:
          span:
          - attributes["k8s.namespace.name"] != "datadog"
    service:
      pipelines:
        logs:
          processors:
          - filter/exclude_all_telemetry_data_from_namespace
  resources:
    limits:
      cpu: 2
      memory: 4Gi
    
cloudProvider: ""
clusterName: onprem-sbx-env
distribution: openshift
environment: sandbox
logsEngine: otel
clusterReceiver:
  k8sObjects:
    - name: pods
      mode: pull
      interval: 5m
    - name: namespaces
      mode: pull
      interval: 5m
    - name: nodes
      mode: pull
      interval: 5m 
    - name: events
      mode: watch
      group: events.k8s.io
  resources:
    limits:
      cpu: 2
      memory: 4Gi

logsCollection:
  containers:
    excludePaths: ["/var/log/pods/datadog_datadog-*/*/*.log"]
    excludeAgentLogs: false
    multilineConfigs:
    - namespaceName:
        value: splunk-otel
      podName:
        value: ocp4-onprem-sbx-splunk-otel-*
        useRegexp: true
      firstEntryRegex: ^\d{4}\-\d{2}\-[0-9T]{3,5}\:\d{2}\:\d{2}\.[0-9Z]{4}
      

  extraFileLogs:
    filelog/audit-log:
      include: [/var/log/kube-apiserver/audit.log]
      start_at: beginning
      include_file_path: true
      include_file_name: false
      resource:
        com.splunk.source: /var/log/kube-apiserver/audit.log
        host.name: 'EXPR(env("K8S_NODE_NAME"))'
        com.splunk.sourcetype: kube:apiserver-audit
    filelog/oauth-audit:
      include: [/var/log/oauth-apiserver/audit.log]
      start_at: beginning
      include_file_path: true
      include_file_name: false
      resource:
        com.splunk.source: /var/log/oauth-apiserver/audit.log
        host.name: 'EXPR(env("K8S_NODE_NAME"))'
        com.splunk.sourcetype: kube:apiserver-audit
    filelog/openshift-audit:
      include: [/var/log/openshift-apiserver/audit.log]
      start_at: beginning
      include_file_path: true
      include_file_name: false
      resource:
        com.splunk.source: /var/log/openshift-apiserver/audit.log
        host.name: 'EXPR(env("K8S_NODE_NAME"))'
        com.splunk.sourcetype: kube:apiserver-audit
splunkPlatform:
  disableCompression: false
  endpoint: https://hecVIP:443/services/collector/event
  idleConnTimeout: 30s
  index: sckl
  insecureSkipVerify: true
  logsEnabled: true
  maxConnections: 200
  metricsEnabled: false
  metricsIndex: sckm
  retryOnFailure:
    enabled: true
    initialInterval: 30s
    maxElapsedTime: 600s
    maxInterval: 60s
  timeout: 60s
  token: xxxx-xxxx-xxx-xxxxx-xxxx
  tracesEnabled: false
  sendingQueue:
    persistentQueue:
      enabled: true
      storagePath: "/var/addon/splunk/exporter_queue"

**Comment by atoulme** [comment]
Please open a support case to follow up as we will need to review your setup. Thanks.
