### ISSUE TITLE
Audit.log doesn't include cluster name

### ISSUE THREAD

**Issue by xxPhuNguyenxx** [signalfx/splunk-otel-collector-chart#1058]
In reviewing the Splunk Otel logs flowing through Splunk, I've noticed the cluster name "k8s.cluster.name" doesn't ever show up. Splunk Connect for Kubernetes does show cluster_name field for all audit.log

**Comment by atoulme** [comment]
Thanks for your report! Please make sure to open a support case to follow up. We are slowly moving away from github issues at this time.
