### ISSUE TITLE
Why does the collector add en event to a logmessage

### ISSUE THREAD

**Issue by zellen** [signalfx/splunk-otel-collector-chart#1136]
### Discussed in https://github.com/signalfx/splunk-otel-collector-chart/discussions/1126

<div type='discussions-op-text'>

<sup>Originally posted by **zellen** January 23, 2024</sup>
We have an application that runs in an app service in Azure and uses Serilog.Sinks.Splunk to send logs directly to the HEC endpoint of Splunk.

Then in our backend, which runs in an AKS-cluster, we use the Splunk Otel Collector to collect our logs and send it to the same HEC endpoint as the app service above.

Both are using the same formatter, SplunkJsonFormatter

Logs that are sent directly from the app service looks like this:
![image](https://github.com/signalfx/splunk-otel-collector-chart/assets/76456/985e8d46-f599-44ef-9b78-222808187bee)

And logs coming from the cluster looks like this where the event is wrapped inside an event: 
![image](https://github.com/signalfx/splunk-otel-collector-chart/assets/76456/b0d7af1b-fac9-4bc0-944d-8aa5d891c03c)

I want both logs to look the same without our backend logs being wrapped in an extra event.
</div>

**Comment by atoulme** [comment]
Please open a support case for further help.
