### ISSUE TITLE
Make hostNetwork optional

### ISSUE THREAD

**Issue by jrcamp** [signalfx/splunk-otel-collector-chart#133]
hostNetwork is currently set to true which may not work for some environments. (Fargate?)

_Originally posted by @dmitryax in https://github.com/signalfx/splunk-otel-collector-chart/issues/127#issuecomment-833963375_

**Comment by jvoravong** [comment]
Related environment that would have issues using hostNetwork:
https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity

**Comment by matthewmodestino** [comment]
+1 

Bump. Could use a helm option that disables hostnetwork, especially for "logging only" daemonsets.

**Comment by atoulme** [comment]
This is now tracked by a Splunk Idea: https://ideas.splunk.com/ideas/EID-I-2101
