### ISSUE TITLE
Not able to add kubernetes metadata for logs collected from additional log files from kubernetes nodes

### ISSUE THREAD

**Issue by ankurnema** [signalfx/splunk-otel-collector-chart#1385]
### Discussed in https://github.com/signalfx/splunk-otel-collector-chart/discussions/1345

<div type='discussions-op-text'>

<sup>Originally posted by **ankurnema** July 18, 2024</sup>
Hello,

We have a usecase where we are trying to tail log files on kubernetes nodes and have configured configuration under below 

```yaml
extraFileLogs: {}
```

For our usecase we are trying to tail log files in kubernetes empty directory from below location

```
/var/lib/kubelet/pods/*/volumes/kubernetes.io~empty-dir/test/test.log
```

In above * usually is pod uid.

Now I want to enrich logs collected with kubernetes metadata by using k8sattributes processor. How can I do this?

As per Code https://github.com/signalfx/splunk-otel-collector-chart/blob/main/helm-charts/splunk-otel-collector/templates/config/_otel-agent.tpl#L743C7-L752C19 there is no option to add any additonal processor.</div>

**Comment by atoulme** [comment]
Please open a support case and we will be happy to provide assistance. See https://splunk.my.site.com/customer/s/need-help/create-case to get started. Thanks!
