### ISSUE TITLE
Default not correclty set

### ISSUE THREAD

**Issue by jdreyesp** [signalfx/splunk-otel-collector-chart#1539]
There's a missing `-` in this line, provoking that when I provision `.Values.serviceAccount.name`, it ends up generating the helm deployment with:

```
 spec:
      serviceAccountName: <my_service_account_name>} }
```

https://github.com/signalfx/splunk-otel-collector-chart/blob/0e083695672ef3055a008964f6c33675dea236f4/helm-charts/splunk-otel-collector/templates/_helpers.tpl#L168

**Comment by jinja2** [comment]
@jdreyesp the hyphen is for removing spaces in go template ([ref](https://pkg.go.dev/text/template#hdr-Text_and_spaces)). And we added some unittest to verify the rendering ([PR](https://github.com/signalfx/splunk-otel-collector-chart/pull/1545)), it is working as expected. If you are still facing this issue, please provide further information to reproduce this.

**Comment by atoulme** [comment]
Closing as inactive. Please open a support request for further help.
