### ISSUE TITLE
How to use with Splunk Enterprise

### ISSUE THREAD

**Issue by gingerwizard** [signalfx/splunk-otel-collector-chart#204]
The docs for this chart state the connector is compatible with Splunk Enterprise. Are there any examples? Its unclear from the chart values how this is supported and what data types? logs/metrics ?
Can we get clarification in the docs?

**Comment by dmitryax** [comment]
Hi @gingerwizard, Splunk Enterprise support is in progress. It should be available in the next release

**Comment by gingerwizard** [comment]
@dmitryax could you possibly differentiate the difference between this project and https://github.com/splunk/sck-otel ? I assumed the historical difference was the lack of splunk enterprise support in this chart. Which of these should be considered the authoritative means of collecting from a k8 cluster for splunk enterprise ingestion?
