### ISSUE TITLE
Collecting Kubernetes Objects and Events

### ISSUE THREAD

**Issue by gingerwizard** [signalfx/splunk-otel-collector-chart#222]
Looking through the chart i cant see equivalent capabilities to https://github.com/splunk/splunk-connect-for-kubernetes/tree/develop/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-objects...how should k8 events be captured? Objects are generally less interesting, although useful, but events are essential.

**Comment by gingerwizard** [comment]
Thanks, @dmitryax yes I think objects and have limited uses and thus are much lower priority.  Great to hear events are being added.

**Comment by gingerwizard** [comment]
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/5047

**Comment by matthewmodestino** [comment]
Any update on when k8s events can be sent out the Splunk platform exporter?

**Comment by elvis-cai** [comment]
+1, could we have https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/k8seventsreceiver or simliar one to send k8s event logs to Splunk cloud?

**Comment by dmitryax** [comment]
OTel k8s events receiver is now adopted by the helm chart https://github.com/signalfx/splunk-otel-collector-chart/pull/478

**Comment by elvis-cai** [comment]
thanks @dmitryax , I can see kube events in Splunk cloud now. 🎉

**Comment by dmitryax** [comment]
I'm closing this issue. 

We are still don't have enough evidence for adding k8s objects support. If anyone thinks that it's required, please submit another issue.
