### ISSUE TITLE
k8sEventsEnabled set to false by default. Can we add documentation for it?

### ISSUE THREAD

**Issue by billg-splunk** [signalfx/splunk-otel-collector-chart#248]
Currently the following section is the default:

```
otelK8sClusterReceiver:
  k8sEventsEnabled: false
```

Can we add a section in:
https://github.com/signalfx/splunk-otel-collector-chart/blob/main/examples/README.md

that explains enabling this to get events?

**Comment by atoulme** [comment]
I have flagged this item for review by our documentation team and will follow up internally. Closing.
