### ISSUE TITLE
Add new Exporter without replacing existing default exporters

### ISSUE THREAD

**Issue by TylerHelmuth** [signalfx/splunk-otel-collector-chart#264]
I'd like to add the logging exporter to my trace pipeline in my agent.  I updated the config section of the otelAgent to look like:

```
otelAgent:
  config: {
    "exporters": {
      "logging"
    },
    "service": {
      "pipelines": {
        "traces": {
          "exporters": [
            "logging"
          ]
        }
      }
    }
  }
```

In the hopes that it would merge the new exporter with the existing defaults.  For the exporters section it worked, but for the trace pipeline's exporters it wiped our sapm and signalfx.  Is that expected or have I setup my values.yaml incorrectly?  Would love to not have to explicitly list "sapm" or "signalfx" in case those change in the future.

**Comment by dmitryax** [comment]
Hi @TylerHelmuth, unfortunately helm supports only deep merge for maps not for lists. Until we have a similar capability on the application side https://github.com/signalfx/splunk-otel-collector, particular pipeline lists has to be fully overridden.

**Comment by TylerHelmuth** [comment]
Bummer guess I'll throw spam and signalfx in there for now. 

Any chance logging would be included in the trace pipeline by default?

**Comment by dmitryax** [comment]
> Any chance logging would be included in the trace pipeline by default?

No, I don't think it'll happen. It's only supposed to be used for debug purposed

**Comment by TylerHelmuth** [comment]
Interesting. In an old version of the collector we are using it to output the number of traces it's collecting, which is then getting ingested into Splunk Core so we can compare the number of traces the collector receives with the number of traces the applications are generating. Is there a different technique we should be doing to get the "number of traces receive by collector" metric into Splunk Core?

**Comment by dmitryax** [comment]
Yes, the collector fetches its own metric and sends them to a configured destination. It has it's own pipeline: https://github.com/signalfx/splunk-otel-collector-chart/blob/main/helm-charts/splunk-otel-collector/templates/config/_otel-agent.tpl#L511

In Observability Suite there is a default OpenTelemetry dashboard that uses those metrics.

**Comment by TylerHelmuth** [comment]
We're doing that too, but having the span count from the collector in Splunk Core along with the application span count logs means we can run searches that compare the numbers and set up monitors.

**Comment by dmitryax** [comment]
@TylerHelmuth you can also send the same metrics to Splunk Core using HEC exporter.

**Comment by TylerHelmuth** [comment]
Perfect. We'll look into that. Thanks

**Comment by notcool11** [comment]
> > Any chance logging would be included in the trace pipeline by default?
> 
> No, I don't think it'll happen. It's only supposed to be used for debug purposes

@dmitryax 

Disagree with this, Observability would say gimme the logs all the time. Could be that the logging level can be tweaked but the act of logging should definitely be defaulted on and easily configurable in the values.yaml.
