### ISSUE TITLE
Add example on how to collect logs from custom host paths

### ISSUE THREAD

**Issue by dmitryax** [signalfx/splunk-otel-collector-chart#307]
Add a configuration example using `extraFileLogs` option added in [this PR](https://github.com/signalfx/splunk-otel-collector-chart/pull/300) with config parameter for mounted volumes.

Discussion reference: https://github.com/signalfx/splunk-otel-collector-chart/pull/300#discussion_r752483728

**Comment by matthewmodestino** [comment]
Would love if we provided example for EmptyDir and persistent Volume Claims. 

I have tested with AzureFile mount successfully with a customer, however admins seem to be keen on using EmptyDir and in cluster storage classes to avoid latency and extra costs. 

Still waiting to hear back on whether AKS even supports collection from EmptyDir or if there are special config consideration/security considerations...

**Comment by evantorrie** [comment]
Yes, I'd also like to see an example (maybe in the rendered manifests) of how to forward logs from an `EmptyDir` volume mount using the Otel Collector as an agent daemonset.

Even better would be to include a way to automatically create a filelog receiver for pods as they are instantiated on the host, which configures the filelog "include" based on an annotation on the pod as to the directory/location of the log file.

**Comment by atoulme** [comment]
Thank you for your recommendations. Please feel free to open Splunk Ideas to follow up if this is still relevant. Closing this issue at this time.
