### ISSUE TITLE
Support for smartagent/kubernetes-apiserver

### ISSUE THREAD

**Issue by TylerHelmuth** [signalfx/splunk-otel-collector-chart#321]
I'm trying to enable Cluster Service metric collection via the OTEL Collector so that the Cluster Services dashboard populates and it _looks_ like Splunk enables that via the [smartagent/kubernetes-apiserver reciever](https://docs.splunk.com/observability/gdi/kubernetes-apiserver/kubernetes-apiserver.html).    Are there plans to update the charts to enable this feature or does it need to be done via the agent/cluster.config section in the values.yaml?

**Comment by TylerHelmuth** [comment]
Actually looks like theres lots of difference receivers to get all those panels to populate.  Is that all done via different versions of the smartagent and if so are there plans to enable that via the charts directly?

**Comment by dmitryax** [comment]
Hi @TylerHelmuth. Thanks for reporting. Yes, we are going to add support of k8s control plane metrics OOTB with this chart. This is in progress.

**Comment by mstumpfx** [comment]
@TylerHelmuth This was released today in v0.44 of the chart. Take a look at [these docs](https://github.com/signalfx/splunk-otel-collector-chart/blob/main/docs/advanced-configuration.md#control-plane-metrics) for more info on how to configure.
