### ISSUE TITLE
Add support for Splunk Observability Profiling

### ISSUE THREAD

**Issue by dmitryax** [signalfx/splunk-otel-collector-chart#332]
## Use case

User wants to send profiling data through OTel agent or gateway, but don't want to collect any logs. Given that profiling data utilizes the same pipeline as logs, currently it's pretty tricky to configure the helm chart for that use case

## Suggested solution

Add another configuration option to explicitly enable profiling support. 

```yaml
splunkObservability:
  profilingEnabled: <true|false> // false by default
```

Under the hood the helm chart should make sure that logs pipeline needed for profiling is created even if logs collection is disabled (`splunkObservability.logsEnabled: false`).

**Comment by chaitanyaphalak** [comment]
So are we going to decompose the logging pipeline into reusable chunks or just add a new pipeline?

**Comment by dmitryax** [comment]
We will be reusing the same pipeline. This change will be applicable only if Splunk Olly Profiling is enabled

**Comment by flands** [comment]
Overall, this seems reasonable to me — one consideration is whether fluentd/otel logs are collected by default — in this case, even with collector being false an agent would be collecting logs and errors would be generated somewhere. Maybe that is not a concern given data setup page will only default to on if entitled. Why default to false though?

**Comment by aunshc** [comment]
Correct me if I am wrong @dmitryax, IIRC that was the initial decision to stay consistent with the splunk-otel-collector since customers and field complained that collector threw errors and wasted resources with logs enabled and they may have other sources of logs being collected. This decision was then translated to the data collection configuration for Kubernetes in the gdi spec here https://github.com/signalfx/gdi-specification/blob/main/specification/configuration.md.

**Comment by dmitryax** [comment]
@flands as decided recently and stated in the GDI spec, logs are disabled by default. So no fluentd or otel logs collection is happening unless user specifies `splunkObservability.logsEnabled=true`. Right now it means that logs pipeline is disabled completely by default. Introducing `splunkObservability.profilingEnabled` makes the logs pipeline dependent on both `splunkObservability.logsEnabled or splunkObservability.profilingEnabled`, while the active logs collection (both otel and fluentd) will be still dependent only on `splunkObservability.logsEnabled`. Whether we want `splunkObservability.profilingEnabled` to be `true` or `false` by default is a product decision, so I'd leave it up to you and @aunshc

**Comment by aunshc** [comment]
@dmitryax Since setting `splunkObservability.profilingEnabled` to be true by default enables the shared pipeline and enabling profiling itself will be done just in the instrumentation configuration, yes, we should do the same in the helm chart as well. LGTM
