### ISSUE TITLE
Add better documentation for logs exclude/include logic

### ISSUE THREAD

**Issue by dmitryax** [signalfx/splunk-otel-collector-chart#344]
We need a section for logs include/exclude capability based on annotation in https://github.com/signalfx/splunk-otel-collector-chart/blob/main/docs/advanced-configuration.md. It should cover both fluentd and native logs collection.

**Comment by matthewmodestino** [comment]
bump, need this updated for customers interested as well. Thanks team!

**Comment by harshit-splunk** [comment]
Added in https://github.com/signalfx/splunk-otel-collector-chart/pull/547
