### ISSUE TITLE
docker images for windows

### ISSUE THREAD

**Issue by beth2016** [signalfx/splunk-otel-collector-chart#348]
From reading , it looks like this chart support windows nodes.   But I cannot find the docker images for windows in either:
repository: splunk/fluentd-hec
or
repository: quay.io/signalfx/splunk-otel-collector

Am I missing something?  thanks.

**Comment by dmitryax** [comment]
@beth2016 Windows images for splunk-otel-collector are here: https://quay.io/repository/signalfx/splunk-otel-collector-windows

Logs collection in windows is not supported yet, so there is no Windows image for splunk/fluentd-hec

**Comment by beth2016** [comment]
@dmitryax thank you!!!
