### ISSUE TITLE
Enabling metrics causes hard to diagnose issue

### ISSUE THREAD

**Issue by bencyoung-Fignum** [signalfx/splunk-otel-collector-chart#380]
We're collecting logs happily into out Splunk Cloud Platform instance, and now want to enable metrics, however when we do so we get an error that's pretty hard to diagnose. Any idea what we do to look into it?

```
2022-02-07T12:00:37.460Z	info	exporterhelper/queued_retry.go:215	Exporting failed. Will retry the request after interval.	{"kind": "exporter", "name": "splunk_hec/platform_metrics", "error": "HTTP 400 \"Bad Request\"; http: read on closed response body", "errorCauses": [{"error": "HTTP 400 \"Bad Request\""}, {"error": "http: read on closed response body"}], "interval": "4.403285946s"}
```

This never corrects itself and no metrics are exported. To set it up I run:

```
helm upgrade my-splunk-otel-collector --set="splunkPlatform.endpoint=https://http-inputs-{myhost}.splunkcloud.com:443/services/collector,splunkPlatform.token={mytoken},splunkPlatform.metricsIndex=aws-kubernetes-metrics,splunkPlatform.index=aws-kubernetes,clusterName=UAT,cloudProvider=aws,distribution=eks,splunkPlatform.metricsEnabled=true" splunk-otel-collector-chart/splunk-otel-collector
```

If I remove ",splunkPlatform.metricsEnabled=true" then all is happy...

**Comment by bencyoung-Fignum** [comment]
Apologies, I've just found that the reason was the index wasn't included in the HEC... Possibly the error could be improved but please feel free to close...

**Comment by dmitryax** [comment]
@rockb1017 we probably need another issue to improve the warning. Probably can be solved by adding `splunkPlatform.metricsEnabled` -> `splunkPlatform.metricsIndex` dependency in `values.schema.json`

**Comment by rockb1017** [comment]
@dmitryax  we do have that check already.
```
"then": {
        "$comment": "then splunkPlatform.metricsIndex must be provided",
        "properties": {
          "splunkPlatform": {
            "if" : {
              "properties": {
                "metricsEnabled": {
                  "const": true
                }
              }
            },
            "then": {
              "properties": {
                "metricsIndex": {
                  "minLength": 1
                }
              }
            }
          }
        }
      }
```
I think this is about metrics index not being associated with HEC token one is using. on the splunk indexer side. 
 I tihnk we should have received the `wrong index` error from splunk HEC, but it didn't. let me take a look
