### ISSUE TITLE
Traces ingestion into Splunk platform

### ISSUE THREAD

**Issue by HiteshDhuria** [signalfx/splunk-otel-collector-chart#381]
Hi all, 
I see a limitation to ingest Otel traces only to Splunk Observability and not to Splunk platform. Is this posses by Splunk itself or is it viable to ingest traces to Splunk platform as well. If so, can this be addressed?
Thanks,
Hitesh

**Comment by dmitryax** [comment]
cc @rockb1017

**Comment by HiteshDhuria** [comment]
Hi @rockb1017 @jodeev   @dmitryax 
Can you pl confirm on this one if the limitation is posed by Splunk or is it for connector alone?
Thanks,
Hitesh

**Comment by atoulme** [comment]
Hi Hitesh, Splunk can consume traces, but they are then rendered as JSON documents. This is not our preferred route: we want to make sure traces can be interpreted in a backend that can associate them together. As such, I am closing the ticket. Please reopen if you have a use case involving Splunk Core which warrants trace ingestion, and we will investigate further.
