### ISSUE TITLE
Error: run as uid (20000) is not supported on Windows

### ISSUE THREAD

**Issue by beth2016** [signalfx/splunk-otel-collector-chart#382]
I am trying to run otel-collector-agent to collect logs for windows in our eks cluster.    

I have logsEngine set to "otel"

The pod is failing to come up with this error:  
Error: run as uid (20000) is not supported on Windows

Am I missing something?  Any input is appreciated.

**Comment by jvoravong** [comment]
Make sure to set isWindows=true in values.yaml
https://github.com/signalfx/splunk-otel-collector-chart/blob/b2dfe48d82b760369c4d3a3f98acb413473cbff4/helm-charts/splunk-otel-collector/values.yaml#L810

**Comment by beth2016** [comment]
@jvoravong That is set to true I'm afraid
isWindows: true

**Comment by beth2016** [comment]
Ah, looks like i have to use use runAsUserName in windows to get passed that error,
