### ISSUE TITLE
Allow filelog include parameter to be set in helm chart 

### ISSUE THREAD

**Issue by matthewmodestino** [signalfx/splunk-otel-collector-chart#395]
As an OTel native logging user, I would like to be able to set what `filelog.include` paths I want to monitor in my helm values to allow me a chance to declaratively target certain workloads upfront. 

This provides an alternative to needing to exclude logs via annotation or needing to set multiple exclude paths after the fact, saving the need to process logs I have no interest in. Instead I can make a conscious decision on what workloads to monitor based on the metadata available in the k8s log paths. 

```
 filelog:
        include:
        - /var/log/pods/*/*/*.log
```

I should be able to set it in the logsCollection section similar to how the `excludePaths` are available. 
```
logsCollection:

  # Container logs collection
  containers:
    enabled: true
    # Container runtime. One of `docker`, `cri-o`, or `containerd`
    # Automatically discovered if not set.
    containerRuntime: ""
    # Paths of logfiles to exclude. object type is array:
    # i.e. to exclude `kube-system` namespace,
    # excludePaths: ["/var/log/pods/kube-system_*/*/*.log"]
    excludePaths: []
    # Boolean for ingesting the agent's own log
    excludeAgentLogs: true
    # Extra operators for container logs.
    # https://github.com/open-telemetry/opentelemetry-log-collection/blob/main/docs/operators/README.md#what-operators-are-available
    extraOperators: []
    multilineConfigs: []
    # Set useSplunkIncludeAnnotation flag to `true` to collect logs from pods with `splunk.com/include: true` annotation and ignore others.
    # All other logs will be ignored.
    useSplunkIncludeAnnotation: false

**Comment by rmfitzpatrick** [comment]
@matthewmodestino this is already possible with the agent config value that merges with the receiver's final configuration:

```
agent:
  config:
    receivers:
      filelog:
        include:
          - my/logs
```

Is this adequate for your use case or is there something else that would be needed?

**Comment by matthewmodestino** [comment]
Ah! Yes it does! I assumed that might be the way! Thanks for confirming!
