### ISSUE TITLE
The default limit_mib seems to be 90% of total memory

### ISSUE THREAD

**Issue by awxfeix** [signalfx/splunk-otel-collector-chart#398]
There is an incorrect description in this file.
https://github.com/signalfx/splunk-otel-collector-chart/blob/a6d71aee2f84a337819f3c21c86c0ab894d6a908/helm-charts/splunk-otel-collector/templates/config/_common.tpl#L8

According to the [code of `splunk-otel-collector`](https://github.com/signalfx/splunk-otel-collector/blob/1d289f68e9896eb58fdea3ef290e83a50774a5b0/cmd/otelcol/main.go#L59), the `defaultMemoryLimitPercentage` is 90%.

**Comment by dmitryax** [comment]
@awxfeix thanks for catching this
