### ISSUE TITLE
Add ability to increase log verbosity for otelcol (not fluentd)

### ISSUE THREAD

**Issue by xamox** [signalfx/splunk-otel-collector-chart#415]
I am running into an issue where I have deployed the collector, I setup one application and it seems to be collecting prometheus metrics fine, I had two others that it is trying to connect but throwing a warning:

`splunk-otel-collector-1647352417-agent-ppx85 otel-collector 2022-03-21T20:10:07.311Z	warn	internal/otlp_metricsbuilder.go:159	Failed to scrape Prometheus endpoint	{"kind": "receiver", "name": "receiver_creator", "scrape_timestamp": 1647893407307, "target_labels": "map[__name__:up instance:10.244.3.27:9999 job:prometheus_simple/10.244.3.27:9999]"}
splunk-otel-collector-1647352417-agent-78czp otel-collector 2022-03-21T20:10:10.436Z	warn	internal/otlp_metricsbuilder.go:159	Failed to scrape Prometheus endpoint	{"kind": "receiver", "name": "receiver_creator", "scrape_timestamp": 1647893410382, "target_labels": "map[__name__:up instance:10.244.5.40:8090 job:prometheus_simple/10.244.5.40:8090]"}`

I have confirmed those endpoints are up and actually have metrics on the exporter endpoints and the annotations match what is on the working deployment.

It would be nice to enable debug level logging to understand what the actual underlying issue maybe. It appears this uses the upstream golang version that supports debug (amongst others) level logging and would like to have this ability here.

**Comment by foram-splunk** [comment]
@jvoravong @dmitryax 

For logLevel changes , what would be the better option?
1. Depreciate fluentd.config.logLevel and use global logLevel config in both fluentd and otel
**OR**
2. Add an example of how to enable debug logging like [this](https://github.com/signalfx/splunk-otel-collector-chart/blob/55efe279c18e5ffdf38acdbca89b30157c13adbc/docs/troubleshooting.md?plain=1#L56)

**Comment by dmitryax** [comment]
The second option should be used. Generally, we don't want to introduce any additional wrappers to what already can be configured with `agent.config`

**Comment by dmitryax** [comment]
@xamox please follow the instruction that @foram-splunk suggested to enable debug logs https://github.com/signalfx/splunk-otel-collector-chart/blob/55efe279c18e5ffdf38acdbca89b30157c13adbc/docs/troubleshooting.md?plain=1#L56

**Comment by atoulme** [comment]
Closing as resolved, please reopen if instructions do not work.
