### ISSUE TITLE
Expose more `recombine` settings in `multilineConfig` section

### ISSUE THREAD

**Issue by matthewmodestino** [signalfx/splunk-otel-collector-chart#417]
As a OTel native logging user, I would like to be able to control advanced use of `recombine` settings for my `multilineConfig` like `combine_with` to make sure my logs look good in the logging backend, or `is_last_entry` or `source_identifier` for advanced multiline reassembly examples.

Really, most of the settings here should be available if the user needs them:

https://github.com/open-telemetry/opentelemetry-log-collection/blob/main/docs/operators/recombine.md#configuration-fields

https://github.com/signalfx/splunk-otel-collector-chart/blob/b673ed480ec10d6041a5c9b710c7df331883adcb/helm-charts/splunk-otel-collector/values.yaml#L433-L463

While I can add them in `extraOperators` the `multilineConfig` section does a great job of writing the rule for the user, just needs some extra advanced controls for custom use cases.

**Comment by matthewmodestino** [comment]
Still need this

**Comment by xxPhuNguyenxx** [comment]
we need as well

**Comment by joem-splunk** [comment]
This is very much needed and would help a lot of customers.

**Comment by matthewmodestino** [comment]
Noticed the "Combine with" setting has been added! Thanks!

https://github.com/signalfx/splunk-otel-collector-chart/blob/main/helm-charts/splunk-otel-collector/values.yaml#L605

**Comment by atoulme** [comment]
Closing!
