### ISSUE TITLE
Confusion regarding "Collector" vs "Connector"

### ISSUE THREAD

**Issue by lindhe** [signalfx/splunk-otel-collector-chart#424]
AFAICT, the use of "Connector" is legacy or a typo or something. I think it should say "Collector" everywhere it says "Connector" today (e.g. in the About section in this repo).

I suggest that we either
a) change all occurrences of Connector to Collector, or
b) clarify in the README what the difference is.

:)

**Comment by atoulme** [comment]
a) is the preferred option. Thanks for your report.
