### ISSUE TITLE
Monitor Splunk availability? 

### ISSUE THREAD

**Issue by ikarlashov** [signalfx/splunk-otel-collector-chart#426]
Hi. 

We're using your chart for exporting splunk logs. We have prometheus monitoring. So we're scraping metrics from 8889 port. 
Although there's a number of metrics, I can't figure out which metrics we need to monitor to get a vision whether splunk endpoint is reachable and logs are being sent (Response code 200 from Splunk endpoint).

We're using latest version **0.47.1**.

**Comment by emaderer** [comment]
You cal look at the **otelcol_exporter_sent_log_records** and **otelcol_exporter_send_failed_log_records** internal collector metrics to see how the HEC exporter is doing.

**Comment by ikarlashov** [comment]
@emaderer 
Thanks.Unfortunately I can't find such metrics. Am I missing something?
![image](https://user-images.githubusercontent.com/23174935/166671973-ecffda71-3967-4068-b209-397e515a4b0e.png)

**Comment by ikarlashov** [comment]
@emaderer Can you elaborate, pls?

**Comment by atoulme** [comment]
@ikarlashov I have recreated with an example this situation, and I see the two metrics Eyal mentions are showing as expected in Prometheus. Here is a PR where I go about creating this example: https://github.com/signalfx/splunk-otel-collector/pull/1856

If you only see metrics related to ingestion of metric points, it is likely you are using the Splunk exporter to export metrics, in which case they will show on a metric pipeline, and use the `otelcol_exporter_sent_metric_points` metric.

Hopefully this helps. I am going to close this issue, please feel free to reopen if you have more questions.
