### ISSUE TITLE
"splunk_hec/platform_logs" and "splunk_hec/platform_metrics" "context deadline exceeded (Client.Timeout exceeded while awaiting headers)" 

### ISSUE THREAD

**Issue by matthewmodestino** [signalfx/splunk-otel-collector-chart#431]
Cross referencing this issue opened against the collector but may be related to helm chart parameter tuning, specifically `http timeouts`

https://github.com/signalfx/splunk-otel-collector-chart/blob/97dc6dca6f04a764a1fe48658453de72ed747a35/helm-charts/splunk-otel-collector/values.yaml#L47-L48

https://github.com/signalfx/splunk-otel-collector/issues/1454

**Comment by atoulme** [comment]
Closing as the linked issue is marked as resolved. Please reopen if this requires further clarification.
