### ISSUE TITLE
splunkObservability.logsEnabled MUST to be true and cannot be disabled (for 0.49.0 or newer)

### ISSUE THREAD

**Issue by awx-kqkq** [signalfx/splunk-otel-collector-chart#470]
After upgrading to 0.49.0 or newer, `splunkObservability.logsEnabled` and cannot be set to false, or the Splunk agent won't start and failed with:

```
main.go:136: application run finished with error: failed to get config: invalid configuration: exporter “splunk_hec/o11y” has invalid configuration: either “log_data_enabled” or “profiling_data_enabled” has to be true
```

It requires at least one of following options to be true
* log_data_enabled
* profiling_data_enabled

A quick troubleshooting shows `profiling_data_enabled` is always false:

https://github.com/signalfx/splunk-otel-collector-chart/blob/main/helm-charts/splunk-otel-collector/templates/config/_otel-k8s-cluster-receiver-config.tpl#L150

and the `log_data_enabled: {{ .Values.splunkObservability.logsEnabled }}` indicates that `splunkObservability.logsEnabled` must be true, or errors above will happen.

Set `splunkObservability.logsEnabled` to `true` may increase our cost on Splunk Observability Cloud.

**Comment by rmfitzpatrick** [comment]
Thanks for your report @awx-kqkq, this should be resolved in https://github.com/signalfx/splunk-otel-collector-chart/releases/tag/splunk-otel-collector-0.53.2.
