### ISSUE TITLE
Add image option in Values Yaml file init container

### ISSUE THREAD

**Issue by kumachop2** [signalfx/splunk-otel-collector-chart#506]
We are  not enabled internet access our cluster and need to point to local registry. Please refer below link and add redhat image option in values.yaml file.

https://github.com/signalfx/splunk-otel-collector-chart/blob/153db1f22d62480c10b7a6cc50d754e1a07a4597/helm-charts/splunk-otel-collector/templates/daemonset.yaml#L139

**Comment by atoulme** [comment]
Closing this issue as the PR #534 offers this possibility. Please comment if more work is needed.
