### ISSUE TITLE
Default Values in Helm Chart cause problems

### ISSUE THREAD

**Issue by fm4991** [signalfx/splunk-otel-collector-chart#519]
When we Install the otel-collector with this [values.yaml](https://github.com/signalfx/splunk-otel-collector-chart/files/9423629/values.yaml.txt) in our k3s clusters we get the following error message:

```
kubectl logs splunk-otel-collector-agent-xl89v
2022/08/23 15:53:28 main.go:225: Set config to [/conf/relay.yaml]
2022/08/23 15:53:28 main.go:291: Set ballast to 165 MiB
2022/08/23 15:53:28 main.go:305: Set memory limit to 450 MiB
Error: failed to get config: cannot unmarshal the configuration: error reading receivers configuration for "filelog": 2 error(s) decoding:

* 'force_flush_period' expected a map, got 'string'
* 'poll_interval' expected a map, got 'string'
2022/08/23 15:53:29 main.go:143: application run finished with error: failed to get config: cannot unmarshal the configuration: error reading receivers configuration for "filelog": 2 error(s) decoding:

* 'force_flush_period' expected a map, got 'string'
* 'poll_interval' expected a map, got 'string'
```
We tried to fix it in serveral playing around with the YAML structure, but in our opinion it is already a map.
In the End we fixed it with commenting the two mentioned values in the agent configmap.
https://github.com/signalfx/splunk-otel-collector-chart/blob/fbf3579fc96dab27a287d344cb67e159dcb988f3/helm-charts/splunk-otel-collector/templates/config/_otel-agent.tpl#L250-L257

**Comment by aryznar-splunk** [comment]
This issue is fixed and delivered.
