### ISSUE TITLE
Migrating from Splunk Connect for Kubernetes on a secure k8s cluster

### ISSUE THREAD

**Issue by mr-miles** [signalfx/splunk-otel-collector-chart#523]
Hi,

I am trying to migrate from SCK (which we've had running fine for some time) to the SOC chart.  I am hitting some obstacles because our cluster on EKS has security policies to restrict the use of containers running as root (etc).

In the SCK chart, there is an option "podSecurityPolicy.create" which we had set to true and then the helm chart deployed fine to the cluster.  However there is no such option in the SOC chart, so its not totally trivial to migrate.

My question is, would it be desirable to add such an option to the chart?  If so (my personal opinion is yes), I can put in a PR for it

**Comment by atoulme** [comment]
Please let us know which version of the chart you are using - our latest release had some changes related to security contraints. We of course would welcome your contribution, thank you!

**Comment by mr-miles** [comment]
Thanks.  I was using 0.58.0 which is latest I think.  I think the security constraints only applied to openshift (I am guessing here, I've never used openshift)

Here's a PR for the pieces:
https://github.com/signalfx/splunk-otel-collector-chart/pull/528

**Comment by dmitryax** [comment]
PSPs are dropped in Kubernetes 1.25. this chart won't be using it https://kubernetes.io/docs/concepts/security/pod-security-policy/
