### ISSUE TITLE
Sonatype Application reported Policy Violations for Quay.io Docker Image v0.56 (quay.io/signalfx/splunk-otel-collector). Please advise plans for remediation steps.

### ISSUE THREAD

**Issue by kumachop2** [signalfx/splunk-otel-collector-chart#531]
Policy Violations for Quay.io Docker Image Scan Build Report for critical.

10 Security-Critical Security cryptography (cp27-cp27m-macosx_10_6_intel) 2.7 (.whl)
10 Security-Critical Security cryptography (cp27-cp27m-manylinux1_x86_64) 2.7 (.whl)
10 Security-Critical Security cryptography (cp27-cp27m-win32) 2.7 (.whl)
10 Security-Critical Security cryptography (cp27-cp27m-win_amd64) 2.7 (.whl)
10 Security-Critical Security cryptography (cp27-cp27mu-manylinux1_x86_64) 2.7 (.whl)
10 Security-Critical Security cryptography (cp34-abi3-macosx_10_6_intel) 2.7 (.whl)
10 Security-Critical Security cryptography (cp34-abi3-manylinux1_x86_64) 2.7 (.whl)
10 Security-Critical Security cryptography (cp34-cp34m-win32) 2.7 (.whl)
10 Security-Critical Security cryptography (cp34-cp34m-win_amd64) 2.7 (.whl)
10 Security-Critical Security cryptography (cp35-cp35m-win32) 2.7 (.whl)
10 Security-Critical Security cryptography (cp35-cp35m-win_amd64) 2.7 (.whl)
10 Security-Critical Security cryptography (cp36-cp36m-win32) 2.7 (.whl)
10 Security-Critical Security cryptography (cp36-cp36m-win_amd64) 2.7 (.whl)
10 Security-Critical Security cryptography (cp37-cp37m-win32) 2.7 (.whl)
10 Security-Critical Security cryptography (cp37-cp37m-win_amd64) 2.7 (.whl)
10 Security-Critical Security cryptography 2.7 (.tar.gz)
10 Security-Critical Security org.apache.hive : hive-exec : 3.1.3
10 Security-Critical Security PyYAML (cp27-cp27m-win32) 5.1.2 (.whl)
10 Security-Critical Security PyYAML (cp27-cp27m-win_amd64) 5.1.2 (.whl)
10 Security-Critical Security PyYAML (cp34-cp34m-win32) 5.1.2 (.whl)
10 Security-Critical Security PyYAML (cp34-cp34m-win_amd64) 5.1.2 (.whl)
10 Security-Critical Security PyYAML (cp35-cp35m-win32) 5.1.2 (.whl)
10 Security-Critical Security PyYAML (cp35-cp35m-win_amd64) 5.1.2 (.whl)
10 Security-Critical Security PyYAML (cp36-cp36m-win32) 5.1.2 (.whl)
10 Security-Critical Security PyYAML (cp36-cp36m-win_amd64) 5.1.2 (.whl)
10 Security-Critical Security PyYAML (cp37-cp37m-win32) 5.1.2 (.whl)
10 Security-Critical Security PyYAML (cp37-cp37m-win_amd64) 5.1.2 (.whl)
10 Security-Critical Security PyYAML (cp38-cp38m-win32) 5.1.2 (.whl)
10 Security-Critical Security PyYAML (cp38-cp38m-win_amd64) 5.1.2 (.whl)
10 Security-Critical Security PyYAML 5.1.2 (.tar.gz)
10 Security-Critical Security ruamel.yaml (py2.py3-none-any) 0.16.5 (.whl)
10 Security-Critical Security ruamel.yaml 0.16.5 (.tar.gz)
9 Security-High Security ansible 2.10.4 (.tar.gz)
9 Security-High Security ansible 2.9.2 (.tar.gz)
9 Security-High Security com.fasterxml.jackson.core : jackson-databind : 2.10.5.1
9 Security-High Security dot 0.1.6
9 Security-High Security moment 2.22.2
9 Security-High Security pip (py2.py3-none-any) 20.1.1 (.whl)
9 Security-High Security py (py2.py3-none-any) 1.8.0 (.whl)
9 Security-High Security py 1.8.0 (.tar.gz)
9 Security-High Security pylint (py3-none-any) 2.4.3 (.whl)
9 Security-High Security pylint 2.4.3 (.tar.gz)
9 Security-High Security urllib3 (py2.py3-none-any) 1.25.3 (.whl)
9 Security-High Security urllib3 1.25.3 (.tar.gz)

**Comment by atoulme** [comment]
Thank you for your report. We typically recommend you upgrade to our latest point release 0.59, as we continuously update our dependencies when releasing.
