### ISSUE TITLE
Unable to run container on Windows 2022 host

### ISSUE THREAD

**Issue by therevoman** [signalfx/splunk-otel-collector-chart#551]
Writing in behalf of customer who is running Kubernetes Windows Nodes and needs splunk installed.  
The helm chart it references the image `quay.io/signalfx/splunk-otel-collector-windows:0.57.0` which appears to have a Windows2019 base.  Customer has hosts that are Windows2022.  

Images are need with a WindowsServer2022 base image, due to known windows container kernel mismatch issues.

**Comment by atoulme** [comment]
We will look at providing a Windows 2022 docker image, the work will happen in https://github.com/signalfx/splunk-otel-collector as part of our Docker distribution.

**Comment by atoulme** [comment]
Hello! We have a dev build for Windows 2022 you can try out here: https://quay.io/repository/signalfx/splunk-otel-collector-windows-dev?tab=tags
Make sure to pick a build tagged with a `-2022` suffix. We will issue an official 2022 build in our next release. Please report any issues!
