### ISSUE TITLE
Missing Steps in documentation for Installing on Hybrid Openshift clusters

### ISSUE THREAD

**Issue by rprakashg-redhat** [signalfx/splunk-otel-collector-chart#561]
Current documentation around installation steps on a Hybrid cluster is missing some steps required for OpenShift

Instructions for windows deployment is missing some config required for scheduler to schedule the daemonset on windows nodes
as described in this document here https://docs.openshift.com/container-platform/4.11/windows_containers/scheduling-windows-workloads.html

if you are trying to collect metrics from just your windows worker nodes you have to make changes in your values.yaml mentioned below

remove below key from tolerations section as we don't want to collect metrics from master nodes

```
  - key: node-role.kubernetes.io/master
    effect: NoSchedule
```

add below to nodeselector section since we are only interested in collecting metrics from windows nodes

```
nodeSelector:
  kubernetes.io/os: 'windows'
```

and then add snippet below to tolerations section
```
tolerations:
  - key: "os"
     operator: "Equal"
     value: "windows"
     effect: "NoSchedule"
```

for linux nodes including master on openshift cluster we recommend following this article to forward logs to SPLUNK
https://cloud.redhat.com/blog/forwarding-logs-to-splunk-using-the-openshift-log-forwarding-api

**Comment by rprakashg-redhat** [comment]
#https://github.com/signalfx/splunk-otel-collector/issues/2075

**Comment by rprakashg-redhat** [comment]
signalfx/splunk-otel-collector/issues/#2075

**Comment by rprakashg-redhat** [comment]
signalfx/splunk-otel-collector/issues#2075

**Comment by matthewmodestino** [comment]
Hey @rprakashg-redhat while we know Red Hat points customers to the log forward api, our customers frequently prefer a dedicated logging agent, for various reasons, including scale, flexibility and customization.

Just a heads up that we will likely continue to recommend the otel logging agent.

**Comment by rprakashg-redhat** [comment]
Sure my point was currently for windows nodes the article I shared does not work and if this solution is being leveraged for windows nodes, you'd typically not going to need to have the agent running on master nodes or even linux nodes right. Documentation should include these type of use cases IMO

**Comment by matthewmodestino** [comment]
Not sure Splunk documentation should cover non Splunk solutions, and most customers I deal with schedule on all nodes including control plane to monitor the entirety of the cluster. Don't usually get asked to only collect partially from the cluster or only on certain nodes, but again, appreciate the feedback! Thanks!

**Comment by rprakashg-redhat** [comment]
Sorry If I'm not making this clear, just saying to include a use case if you are using otel collector to just collect metrics from windows nodes, those changes I suggested might be worth including in docs.

**Comment by rprakashg-redhat** [comment]
I was working with a customer who wanted to use the otel collector to collect metrics from windows nodes, they were happy with the ootb solution they get with Openshift. they ran into issues with the deployment and had to help them. That's what prompted me to log this request for documentation update :)

**Comment by atoulme** [comment]
Thank you for this report. Please open a support case for further requests for help.
