### ISSUE TITLE
Need instructions to add receivers and services into values.yaml on helm chart

### ISSUE THREAD

**Issue by rohits-splunk** [signalfx/splunk-otel-collector-chart#575]
I am trying to ingest custom application metrics into o11y cloud , need instructions on how to add receivers and services on the helm chart ( values.yaml ) , tried adding like the usual agent config but it didn't allow me.

Please help update instructions to make this clearer.

**Comment by atoulme** [comment]
Please make a request via Splunk Ideas. Thanks!
