### ISSUE TITLE
Stack smashing error when executing bash

### ISSUE THREAD

**Issue by connorM43** [signalfx/splunk-otel-collector-chart#586]
I'm experiencing an interesting error across multiple EKS and AKS clusters after installing the helm chart. Upon either trying to terminal into a pod or when the secret validation job attempts to run, there's a fatal error as defined below:

```
*** stack smashing detected ***: <unknown> terminated
```

This is using `v0.62.0` of the chart. We have tried with our config changes (e.g. additional receivers) as well as a straight fresh install with the below:

```
helm install test-splunk-otel-collector --set="splunkObservability.realm=us0,splunkObservability.accessToken=REDACTED,clusterName=azure-staging" splunk-otel-collector-chart/splunk-otel-collector
```

This is occurring consistently on EKS 1.22 and AKS 1.22 clusters. We don't see anything else in the logs potentially relevant (as far as we can tell, at least). We also submitted a ticket with Splunk, but it was closed right away with only a suggestion to check sizing. We did try massively scaling up the resources, but this had no effect.

The collector is running perfectly fine and sending metrics as expected. Deployments in ArgoCD won't work nominally due to the failing validation job. Additionally, we are unable to terminal into any of the collector containers. This impedes our ability to have confidence in the sustainment of these deployments in Production.

**Comment by atoulme** [comment]
Please reopen the case, linking to this issue, so we have maximum air cover. Please make sure to report in the case that it is not solved.

Would you please indicate exactly how to reproduce the bug? When you mention trying to terminal into a pod, do you mean you are trying to execute the command `kubectl exec -it -- pod sh`?
By any chance, have you seen this happen elsewhere, or have you replicated this issue elsewhere?
You pasted a fatal error above. Is this error pasted as stdout, or is it in a log file, or the pod logs?
Do you see anything else in the logs? Any stacktrace?

Thank you!

**Comment by atoulme** [comment]
Please also indicate your own OS and kubectl version.
