### ISSUE TITLE
Disabling internal metrics

### ISSUE THREAD

**Issue by Jylhis** [signalfx/splunk-otel-collector-chart#590]
Hi,

I would like to use otel collector to only send metrics from specific namespaces. How can I disable sending of the internal metrics, specifically `otelcol`?

I have setup exclude filter for containers, but these doesn't seem to have effect for internal metrics.

**Comment by Jylhis** [comment]
Thank you for the link. The problem why my filter didn't catch those metrics was that it was defined for `metrics` service and not `metrics/collector`. 

I agree that the metrics are useful, but for my niche use case I need them disabled (or at least not exported to a same place).

The way I implemented it for now was to create new processor that defines regex of namespaces I don't want to be monitored, and I set that processor for all the relevant services. Probably not the most optimal solution but works for now. I will look into updating the helm chart for proper solution.

**Comment by atoulme** [comment]
This is a valid approach, you can use the filterprocessor to get the job done. Closing as resolved.
