### ISSUE TITLE
`multilineConfig` AND `extraOperators` cannot BOTH be set in values.yaml, `extraOperators` will be skipped

### ISSUE THREAD

**Issue by matthewmodestino** [signalfx/splunk-otel-collector-chart#633]
Hi Team, 

Just a heads up. Currently if you try to use `multilineConfig` AND `extraOperators` your `extraOperators` will be skipped due to the nature of the rules we render from `multilineConfig`. 

As a workaround, I stole the rendered multiline rules from the configmap and commented out the `multilineConfig` in values.yaml, and put all the rules under `extraOperators` to control the flow of events.

**Comment by VihasMakwana** [comment]
@matthewmodestino I'm trying to reproduce this, but I am getting both `multilineConfig` AND `extraOperators` in my configmap. Is this issue somehow fixed? If not, can you please attach the steps to reproduce?

**Comment by matthewmodestino** [comment]
@VihasMakwana they will render in the configMap but the ordering and precedence can be an issue if the rules output to a subsequent operator and skips the rules.
