### ISSUE TITLE
Metric Index definition using Annotations

### ISSUE THREAD

**Issue by gseyerl** [signalfx/splunk-otel-collector-chart#635]
Hello,
we are able to use annotations in order to define different indexes for log ingestion:
https://github.com/signalfx/splunk-otel-collector-chart/blob/main/docs/advanced-configuration.md#managing-log-ingestion-by-using-annotations

We would need a similar possibility for metrics. 

Best
G

**Comment by VihasMakwana** [comment]
@gseyerl We do support annotations for metrics as well, the docs aren't updated I guess. But I can see, we have a similar functionality in place by looking at the code. Can you try it out?

**Comment by VihasMakwana** [comment]
Yeah, I misunderstood this. 
We have it in [core](https://github.com/open-telemetry/opentelemetry-collector-contrib), but not in our chat repo.
@atoulme can you assign it to me? It looks pretty straightforward to implement.

**Comment by atoulme** [comment]
I have created this Splunk idea to track this enhancement request: https://ideas.splunk.com/ideas/EID-I-2131

**Comment by atoulme** [comment]
Closing - please follow the Splunk idea record to watch for developments on this.

**Comment by sbylica-splunk** [comment]
Implemented in v 0.92:
https://github.com/signalfx/splunk-otel-collector-chart/releases/tag/splunk-otel-collector-0.92.0

**Comment by gseyerl** [comment]
Hi, 
nice thank you. Looking forward to try it out.
Best 
G
