### ISSUE TITLE
No logs sent to Splunk, Raise warning when we cannot follow symlink

### ISSUE THREAD

**Issue by matthewmodestino** [signalfx/splunk-otel-collector-chart#637]
Hey Team, 

Had a call with a customer today, where they had a custom volume for docker based kubernetes logs. 

Instead of the default `/var/lib/docker/containers` mount, we had to update their settings to include the proper destination file path for their environment. ie. `/var/foo/docker/containers`:

https://github.com/signalfx/splunk-otel-collector-chart/blob/921de2890bde494aeb52756036dcb1cc11fcc5e2/helm-charts/splunk-otel-collector/values.yaml#L380-L383

The collector did not raise any warns or errors about not finding logs or having permissions to follow the symlink. Looked like it was running normally. 

The user experience was no logs being send, while we could see metrics. Would have vastly simplified troubleshooting if pod logs showed we couldn't open the symlink from `/var/log/pods`. 

This may only be relevant with Docker based clusters. So not sure how important it is, but figured I'd share.

**Comment by VihasMakwana** [comment]
@matthewmodestino Did the collector showed following logs?
```Started watching file path: XYZ```
