### ISSUE TITLE
Unable to monitor kube-apiserver metrics with receiver_creator

### ISSUE THREAD

**Issue by govardha** [signalfx/splunk-otel-collector-chart#641]
Hello,

I have a pretty standard k8s cluster on prem.  The one final block I am running into is getting metrics from the kube-apiserver.

I have the `receiver_creator` configured with multiple rules and all of them are firing save for this one.  When I exec it into an agent in one of the controllers, I am able to use the serviceAccount tokens to successfully scrape the api server metrics that runs on that node.  

I initially thought the RBAC did not specify `endpoints` and that was the issue, I added that but that did not help either.  

I would greatly appreciate any pointers in this topic now as I am just stumped.

Thank you!
g

**Comment by atoulme** [comment]
I have confirmation that this is with 1.21, on an onprem cluster built with kubeadmin.

**Comment by omrozowicz-splunk** [comment]
Hey @govardha, it would help if you can share with me what labels do you have in `kube-apiserver` pod. 
The filter in `receiver_creator` is based on having `k8s-app=kube-apiserver` label, and maybe this is not true for every k8s distribution.
The command to check that is:
```
kubectl describe pod/<kube-apiserver-pod-id> -n kube-system
```

**Comment by govardha** [comment]
Hello @omrozowicz-splunk 

Thanks for responding, I did make sure the label is configured appropriately to scrape the kube-apiserver metrics.  

I know this works, as I tweaked the rules to get all the other control plane items methods scraped and this is the only one that doesn't work.  All the other `receiver_creator` once I got the labels appropriately tweaked started working save for this one.

**Comment by govardha** [comment]
With @omrozowicz-splunk's assistance I got this sorted out.  The key point was the ` kube-apiserver` static pod description in my on prem set up did not have a `Port` or `Host Port` field, hence the `receiver_creator` rule found [here](https://github.com/signalfx/splunk-otel-collector-chart/blob/f4cf82bedf200982040e0bb367d58261662b2a2a/rendered/manifests/metrics-only/configmap-agent.yaml#L198) wasn't actually triggering

`rule: type == "port" && port == 443 && pod.labels["k8s-app"] == "kube-apiserver"`

Once I modified the above rule in my agent `configmap` in the `.Values.agent.config` in the helm chart to look like this, things started working and I started scraping metrics from all 3 pods of my `kube-apiserver`

```
rule: type == "pod" && labels["component"] == "kube-apiserver"
  config:
    extraDimensions:
      metric_source: kubernetes-apiserver
    port: 6443
    skipVerify: true
    type: kubernetes-apiserver
    useHTTPS: true
    useServiceAccount: true
```

Thank you to both @atoulme & @omrozowicz-splunk for your assistance with this.
