### ISSUE TITLE
Update docs to advise that Splunk Enterprise users how to configure indexed fields that OTel sends. 

### ISSUE THREAD

**Issue by matthewmodestino** [signalfx/splunk-otel-collector-chart#645]
Hi Team, 

Found a key piece of SCK docs that we need to include on the OTel side, specifically:

https://github.com/splunk/splunk-connect-for-kubernetes#searching-for-sck-metadata-in-splunk

Splunk Connect for Kubernetes sends events to Splunk which can contain extra meta-data attached to each event. Metadata values such as "pod", "namespace", "container_name","container_id", "cluster_name" will appear as fields when viewing the event data inside Splunk. There are two solutions for running searches in Splunk on meta-data.

Modify search to usefieldname::value instead of fieldname=value.

Configure fields.conf on your downstream Splunk system to have your meta-data fields available to be searched using fieldname=value. 

Example: [fields.conf.example](https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/fields.conf.example)

For more information on index time field extraction please view this [guide](https://docs.splunk.com/Documentation/Splunk/latest/Data/Configureindex-timefieldextraction#Where_to_put_the_configuration_changes_in_a_distributed_environment).

**Comment by matthewmodestino** [comment]
Looks like in Splunk 9.0+ we default `always_include_indexedfield_lispy ` to true, so users on newer versions or in cloud shouldn't have an issue searching for indexed fields by default.

However still good to mention the logic on how to manually add indexed fields for folks on older versions or who prefer the performance gains of disabling this and manually configuring search to look for our kubernetes fields.  

```
always_include_indexedfield_lispy = <boolean>
* Whether or not search always looks for a field that does not have
  "INDEXED = true" set in fields.conf using both the indexed and non-
  indexed forms.
* If set to "true", when searching for <field>=<value>, the lexicon is
  searched for both "<field>::<value>" and "<value>".
* If set to "false", when searching for <field>=<val>, the lexicon is
  searched only for "<value>".
* Set to "true" if you have fields that are sometimes indexed and
  sometimes not indexed.
* For field names that are always indexed, it is much better
  for performance to set "INDEXED = true" in fields.conf for
  that field instead.
* Default: true
```

**Comment by sbylica-splunk** [comment]
Update to the docs done:
https://github.com/signalfx/splunk-otel-collector-chart/pull/1059

**Comment by atoulme** [comment]
Closing as completed.
