### ISSUE TITLE
Having issues with pod initializing after v0.68.0 upgrade

### ISSUE THREAD

**Issue by kumachop2** [signalfx/splunk-otel-collector-chart#650]
Team, 
 I have changed the agent security context mentioned below to remediate Azure defender recommendation on Running containers as root user should be avoided for agent version v0.58.0. I have not faced issues later.  Recently upgraded agent from v0.63.0 to v0.68.0 and pod is not initializing, hence changed runAsUser to 0 for bring pod online.  I do spotted change PR on security fix but not clear. (https://github.com/signalfx/splunk-otel-collector-chart/pull/617)

**daemonset.yaml**
        - name: patch-log-dirs
          securityContext:
            runAsUser: 20000

agent:
  enabled: true
  securityContext:
    runAsUser: 20000
    runAsGroup: 20000

Init:Error 

Error from server (BadRequest): container "otel-collector" in pod "*****-splunk-otel-collector-agent-2rnnr" is waiting to start: PodInitializing

Pod Describe:

Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  2m47s                 default-scheduler  Successfully assigned splunk-aks-nonprod/******-splunk-otel-collector-agent-2rnnr to aks-userpool-17658552-vmss000004
  Normal   Pulling    2m46s                 kubelet            Pulling image "repository: quay.io/signalfx/splunk-otel-collector:0.68.0"
  Normal   Pulled     2m46s                 kubelet            Successfully pulled image "repository: quay.io/signalfx/splunk-otel-collector:0.68.0" 
in 548.599006ms
  Normal   Created    2m46s                 kubelet            Created container migrate-checkpoint
  Normal   Started    2m46s                 kubelet            Started container migrate-checkpoint
  Normal   Pulled     2m45s                 kubelet            Successfully pulled image "registry.access.redhat.com/ubi9/ubi" in 306.735414ms
  Normal   Pulled     2m44s                 kubelet            Successfully pulled image "registry.access.redhat.com/ubi9/ubi" in 118.347517ms
  Normal   Pulled     2m27s                 kubelet            Successfully pulled image "registry.access.redhat.com/ubi9/ubi" in 167.397981ms
  Normal   Pulling    2m1s (x4 over 2m45s)  kubelet            Pulling image "registry.access.redhat.com/ubi9/ubi"
  Normal   Created    2m1s (x4 over 2m45s)  kubelet            Created container patch-log-dirs
  Normal   Pulled     2m1s                  kubelet            Successfully pulled image "registry.access.redhat.com/ubi9/ubi" in 93.484179ms
  Normal   Started    2m (x4 over 2m45s)    kubelet            Started container patch-log-dirs
  Warning  BackOff    2m (x5 over 2m43s)    kubelet            Back-off restarting failed container
  
Please advice on next steps.

Thank You

**Comment by harshit-splunk** [comment]
Hey @kumachop2, are you modifying the daemonset template? It is not recommended to modify the template files unless you are absolutely sure about your requirements.

The `patch-log-dirs` init container must be run as the root user, because it grants read permission to the non-root user using ACLs(Access Control List).

You should use values.yaml file to run the agent as non-root user.
https://github.com/signalfx/splunk-otel-collector-chart/blob/52d7534d220ab0b9a6703f3b7132a314beb807f5/helm-charts/splunk-otel-collector/values.yaml#L360-L362

**Comment by kumachop2** [comment]
@harshit-splunk Thank You for prompt response. Initially I tried to limit configuration for non-root user with values.yaml but it didn't remediated. Later changed the daemonset template to resolve part of agent v0.58.0 upgrade. I did reviewed with Splunk PS prior to implementing changes in daemonset template. The work around helped  for a while and resurfaced again with latest version v0.68.0.

Based on your inputs reverted daemonset template changes  to 0 and set the securityContext to non zero in values yaml. All agents started but defender reported as affected components. I'm not seeing compliance issues with Gateway and Receiver pods. 

I'm looking to remediate below defender issues, please do advice.

1. Running containers as root user should be avoided  - Still open 

2. Usage of host networking and ports should be restricted  - Security policy parameters: allow host network usage, and min and max host ports - need direction to update values.yaml or alternate option 

3. Container with privilege escalation should be avoided  - Need to  add AllowPrivilegeEscalation flag to 'false' but no reference in values.yaml.

**Comment by harshit-splunk** [comment]
> 1. Running containers as root user should be avoided  - Still open

Can you please provide your values.yaml config along with the name of the container that is running as a root user? It is possible that you are using the fluentd logsEngine. Running as a non-root user is not supported for fluentd.

> 2. Usage of host networking and ports should be restricted  - Security policy parameters: allow host network usage, and min and max host ports - need direction to update values.yaml or alternate option

As of now, the host network can not be disabled as it is required to collect the underlying node's networking metrics.

> 3. Container with privilege escalation should be avoided  - Need to add AllowPrivilegeEscalation flag to 'false' but no reference in values.yaml.

You can add the flag along with `runAsUser` setting. For example:
```yaml
securityContext:
  allowPrivilegeEscalation: false
  runAsUser: 20000
  runAsGroup: 20000
```

**Comment by kumachop2** [comment]
Thanks Harshit for response. I'm using otel engine for logs. Container name is otel-collector. Yes I did tried adding the flag along with runAsUser setting part of v0.63.0 upgrade but didn't work. Sure I'll try with v0.68.0 and revert. Here is partial values yaml file.
logsEngine: otel
splunkObservability:
  realm: us0
  accessToken: ***********
  metricsEnabled: true
  tracesEnabled: true
  logsEnabled: true
  profilingEnabled: true
  infrastructureMonitoringEventsEnabled: true  
clusterReceiver:
  enabled: true
  eventsEnabled: true  
  resources:
    limits:
      cpu: 1
      memory: 2Gi
  securityContext:
    runAsUser: 20000
    runAsGroup: 20000
logsCollection:
  # Container logs collection
  containers:
    enabled: true
    # Enable the logs from the collector/agent to be collected at the container level
    excludeAgentLogs: true    
agent:
  enabled: true
  resources:
    limits:
      cpu: 1    
      memory: 2Gi
    requests:
      cpu: 200m
      memory: 500Mi        
  securityContext:
    runAsUser: 20000
    runAsGroup: 20000
    runAsNonRoot: true 
    allowPrivilegeEscalation: false

**Comment by kumachop2** [comment]
@harshit-splunk, Just let you know that I was successful with upgrade from v0.63.0 to v0.66.0 with daemonset template change. Also I do noticed the the difference between v0.63.0/v0.66.0 and v0.68.0 is with acl mentioned below.
**v0.63.0/v0.66.0**
         if [ -d "/var/log/pods" ];
          then
              setfacl -n -Rm d:g:{{ $agent.securityContext.runAsGroup | default 20000 }}:rx,g:{{ $agent.securityContext.runAsGroup | default 20000 }}:rx /var/log/pods;
**v0.68.0**
              setfacl -n -Rm d:m::rx,m::rx,d:g:{{ $agent.securityContext.runAsGroup | default 20000 }}:rx,g:{{ $agent.securityContext.runAsGroup | default 20000 }}:rx /var/log/pods;
          fi;
          {{- end }}
          {{- if .Values.logsCollection.journald.enabled }}

**Comment by atoulme** [comment]
Closing as fixed.

**Comment by kumachop2** [comment]
@atoulme This issue still open I did provided additional information earlier.

**Comment by atoulme** [comment]
Apologies, @kumachop2, I am not quite sure what the issue is. I understand that you were successful in upgrading. What is the remaining problem? @harshit-splunk please feel free to jump in.

**Comment by kumachop2** [comment]
@atoulme The issue is, I'm not able to upgrade agent from v0.63.0/v0.66.0 to v0.68.0 due to agent pod initialization error. Part of my troubleshooting I did spotted setacl in daemonset template was updated, which reported earlier but not sure that is causing issue. @harshit-splunk Please do share your observations or next steps.

**Comment by harshit-splunk** [comment]
@kumachop2, can you share the init container's logs?
```bash
kubectl get logs <otel-agent-name> -c patch-log-dirs
```

Also, can you share the full response of the `kubectl describe` command?

**Comment by kumachop2** [comment]
@harshit-splunk  Thank you for your response and please find below the requested information and revert for additional info.

**Container logs for initialization error pod**

ownership of '/var/addon/splunk/otel_pos/receiver_filelog_' retained as 20000:20000
ownership of '/var/addon/splunk/otel_pos' retained as 20000:20000
mode of '/var/addon/splunk/otel_pos' retained as 2775 (rwxrwsr-x)
setfacl: /var/log/pods/splunk-***-***_*******-splunk-otel-collector-agent-94flg_8bfdb9f6-8a56-4ffd-882c-c5d4f9be743e/migrate-checkpoint/0.log: Operation n
ot permitted
setfacl: /var/log/pods/splunk-***-***_*******-splunk-otel-collector-agent-94flg_8bfdb9f6-8a56-4ffd-882c-c5d4f9be743e/patch-log-dirs/3.log: Operation not p
ermitted
setfacl: /var/log/pods/splunk-***-***_*******-splunk-otel-collector-agent-94flg_8bfdb9f6-8a56-4ffd-882c-c5d4f9be743e/patch-log-dirs/4.log: Operation not p
ermitted
setfacl: /var/log/pods/splunk-***-***_*******-splunk-otel-collector-7b9db788dc-wg8nk_cd6cc40f-f51a-43d0-bee5-4de7d3f43093/otel-collector/0.log: Operation 
not permitted

**Full response of the kubectl describe command for initialization error pod**

Name:             *******-splunk-otel-collector-agent-94flg
Namespace:        splunk-***-***
Priority:         0
Service Account:  *******-splunk-otel-collector
Node:             aks-userpool-17658552-vmss000000/**.**.**.**
Start Time:       Tue, 07 Feb 2023 15:18:24 +0000
Labels:           app=splunk-otel-collector
                  controller-revision-hash=578957bcf7
                  pod-template-generation=1
                  release=*******-splunk-otel-collector
Annotations:      checksum/config: 70c2e200dfe2cdb6c0b6209074a05b3e8697efe48b7b385ffeae901fb431d709
                  kubectl.kubernetes.io/default-container: otel-collector
Status:           Pending
IP:               **.**.**.**
IPs:
  IP:           **.**.**.**
Controlled By:  DaemonSet/*******-splunk-otel-collector-agent
Init Containers:
  migrate-checkpoint:
    Container ID:  containerd://1b6f72933d681f72c0124824d83fb202c18dd55e4988d4e171152ef02c95069d
    Image:         *******.azurecr.io/splunk-otel-collector:0.70.0
    Image ID:      *******.azurecr.io/splunk-otel-collector@sha256:c548f2054509ca72222cc7cb1e66bd18dc8152fef784b8a874ca68043484c30f
    Port:          <none>
    Host Port:     <none>
    Command:
      /migratecheckpoint
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Tue, 07 Feb 2023 15:18:25 +0000
      Finished:     Tue, 07 Feb 2023 15:18:25 +0000
    Ready:          True
    Restart Count:  0
    Environment:
      CONTAINER_LOG_PATH_FLUENTD:  /var/log/splunk-fluentd-containers.log.pos
      CONTAINER_LOG_PATH_OTEL:     /var/addon/splunk/otel_pos/receiver_filelog_
      CUSTOM_LOG_PATH_FLUENTD:     /var/log/splunk-fluentd-*.pos
      CUSTOM_LOG_PATH_OTEL:        /var/addon/splunk/otel_pos/receiver_filelog_
      CUSTOM_LOG_CAPTURE_REGEX:    \/var\/log\/splunk\-fluentd\-(?P<name>[\w0-9-_]+)\.pos
      JOURNALD_LOG_PATH_FLUENTD:   /var/log/splunkd-fluentd-journald-*.pos.json
      JOURNALD_LOG_PATH_OTEL:      /var/addon/splunk/otel_pos/receiver_journald_
      JOURNALD_LOG_CAPTURE_REGEX:  \/splunkd\-fluentd\-journald\-(?P<name>[\w0-9-_]+)\.pos\.json
    Mounts:
      /var/addon/splunk/otel_pos from checkpoint (rw)
      /var/lib/docker/containers from varlibdockercontainers (rw)
      /var/log from varlog (rw)
  patch-log-dirs:
    Container ID:  containerd://dc82cd295ce1dbfd7a927c82703bb3f73c709e04c15eb698b5a0bc3e09333453
    Image:         *******.azurecr.io/ubi
    Image ID:      *******.azurecr.io/ubi@sha256:7977a31c6829d4629698ae5f3dcd5691e90f83bed1b336bff16d2afafa12cba4
    Port:          <none>
    Host Port:     <none>
    Command:
      sh
      -c
       mkdir -p /var/addon/splunk/otel_pos; chown -Rv 20000:20000 /var/addon/splunk/otel_pos; chmod -v g+rwxs /var/addon/splunk/otel_pos; if [ -d "/var/lib/docke
r/containers" ]; then setfacl -n -Rm d:m::rx,m::rx,d:g:20000:rx,g:20000:rx /var/lib/docker/containers; fi; if [ -d "/var/log/crio/pods" ]; then setfacl -n -Rm d:
m::rx,m::rx,d:g:20000:rx,g:20000:rx /var/log/crio/pods; fi; if [ -d "/var/log/pods" ]; then setfacl -n -Rm d:m::rx,m::rx,d:g:20000:rx,g:20000:rx /var/log/pods; f
i;
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Tue, 07 Feb 2023 15:20:01 +0000
      Finished:     Tue, 07 Feb 2023 15:20:01 +0000
    Ready:          False
    Restart Count:  4
    Environment:    <none>
    Mounts:
      /var/addon/splunk/otel_pos from checkpoint (rw)
      /var/lib/docker/containers from varlibdockercontainers (rw)
      /var/log from varlog (rw)
Containers:
  otel-collector:
    Container ID:  
    Image:         *******.azurecr.io/splunk-otel-collector:0.70.0
    Image ID:      
    Ports:         8006/TCP, 14250/TCP, 14268/TCP, 4317/TCP, 4318/TCP, 55681/TCP, 9080/TCP, 9943/TCP, 9411/TCP
    Host Ports:    8006/TCP, 14250/TCP, 14268/TCP, 4317/TCP, 4318/TCP, 55681/TCP, 9080/TCP, 9943/TCP, 9411/TCP
    Command:
      /otelcol
      --config=/conf/relay.yaml
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     1
      memory:  2Gi
    Requests:
      cpu:      200m
      memory:   500Mi
    Liveness:   http-get http://:13133/ delay=0s timeout=1s period=10s #success=1 #failure=3
    Readiness:  http-get http://:13133/ delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      SPLUNK_MEMORY_TOTAL_MIB:            2048
      K8S_NODE_NAME:                       (v1:spec.nodeName)
      K8S_NODE_IP:                         (v1:status.hostIP)
      K8S_POD_IP:                          (v1:status.podIP)
      K8S_POD_NAME:                       *******-splunk-otel-collector-agent-94flg (v1:metadata.name)
      K8S_POD_UID:                         (v1:metadata.uid)
      K8S_NAMESPACE:                      splunk-***-*** (v1:metadata.namespace)
      SPLUNK_OBSERVABILITY_ACCESS_TOKEN:  <set to the key 'splunk_observability_access_token' in secret 'splunk-otel-collector'>  Optional: false
      HOST_PROC:                          /hostfs/proc
      HOST_SYS:                           /hostfs/sys
      HOST_ETC:                           /hostfs/etc
      HOST_VAR:                           /hostfs/var
      HOST_RUN:                           /hostfs/run
      HOST_DEV:                           /hostfs/dev
      HOST_PROC_MOUNTINFO:                /proc/self/mountinfo
    Mounts:
      /conf from otel-configmap (rw)
      /hostfs/dev from host-dev (ro)
      /hostfs/etc from host-etc (ro)
      /hostfs/proc from host-proc (ro)
      /hostfs/run/udev/data from host-run-udev-data (ro)
      /hostfs/sys from host-sys (ro)
      /hostfs/var/run/utmp from host-var-run-utmp (ro)
      /var/addon/splunk/otel_pos from checkpoint (rw)
      /var/lib/docker/containers from varlibdockercontainers (ro)
      /var/log from varlog (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from token (ro)
Conditions:
  Type              Status
  Initialized       False 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  varlog:
    Type:          HostPath (bare host directory volume)
    Path:          /var/log
    HostPathType:  
  varlibdockercontainers:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/docker/containers
    HostPathType:  
  checkpoint:
    Type:          HostPath (bare host directory volume)
    Path:          /var/addon/splunk/otel_pos
    HostPathType:  DirectoryOrCreate
  host-dev:
    Type:          HostPath (bare host directory volume)
    Path:          /dev
    HostPathType:  
  host-etc:
    Type:          HostPath (bare host directory volume)
    Path:          /etc
    HostPathType:  
  host-proc:
    Type:          HostPath (bare host directory volume)
    Path:          /proc
    HostPathType:  
  host-run-udev-data:
    Type:          HostPath (bare host directory volume)
    Path:          /run/udev/data
    HostPathType:  
  host-sys:
    Type:          HostPath (bare host directory volume)
    Path:          /sys
    HostPathType:  
  host-var-run-utmp:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/utmp
    HostPathType:  
  otel-configmap:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      *******-splunk-otel-collector-otel-agent
    Optional:  false
  token:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  jenius-splunk-otel-collector-token-vws76
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  kubernetes.io/os=linux
Tolerations:     node-role.kubernetes.io/master:NoSchedule
                 node.kubernetes.io/disk-pressure:NoSchedule op=Exists
                 node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                 node.kubernetes.io/network-unavailable:NoSchedule op=Exists
                 node.kubernetes.io/not-ready:NoExecute op=Exists
                 node.kubernetes.io/pid-pressure:NoSchedule op=Exists
                 node.kubernetes.io/unreachable:NoExecute op=Exists
                 node.kubernetes.io/unschedulable:NoSchedule op=Exists
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  3m                     default-scheduler  Successfully assigned splunk-***-***/*******-splunk-otel-collector-agent-94flg to aks-user
pool-17658552-vmss000000
  Normal   Pulling    3m                     kubelet            Pulling image "*******.azurecr.io/splunk-otel-collector:0.70.0"
  Normal   Pulled     2m59s                  kubelet            Successfully pulled image "*******.azurecr.io/ubi" in 124.999385ms
  Normal   Created    2m59s                  kubelet            Created container migrate-checkpoint
  Normal   Started    2m59s                  kubelet            Started container migrate-checkpoint
  Normal   Pulled     2m59s                  kubelet            Successfully pulled image "*******.azurecr.io/splunk-otel-collector:0.70.0"
 in 317.740912ms
  Normal   Pulled     2m58s                  kubelet            Successfully pulled image "*******.azurecr.io/ubi" in 95.000297ms
  Normal   Pulled     2m41s                  kubelet            Successfully pulled image "*******.azurecr.io/ubi" in 128.829817ms
  Normal   Pulling    2m13s (x4 over 2m59s)  kubelet            Pulling image "*******.azurecr.io/ubi"
  Normal   Created    2m13s (x4 over 2m59s)  kubelet            Created container patch-log-dirs
  Normal   Started    2m13s (x4 over 2m58s)  kubelet            Started container patch-log-dirs
  Warning  BackOff    2m13s (x5 over 2m57s)  kubelet            Back-off restarting failed container
  Normal   Pulled     2m13s                  kubelet            Successfully pulled image "*******.azurecr.io/ubi" in 114.289389ms
 
**Container logs for successful initialized Agent pod**
  
  -c patch-log-dirs
ownership of '/var/addon/splunk/otel_pos/receiver_filelog_' retained as 20000:20000
ownership of '/var/addon/splunk/otel_pos' retained as 20000:20000
mode of '/var/addon/splunk/otel_pos' retained as 2775 (rwxrwsr-x)

**Comment by harshit-splunk** [comment]
`Operation not permitted` -> It looks like the `patch-log-dirs` init container doesn't have root permissions here. Can you provide the object of the agent deployment?

```
kubectl get deployment <deployment-name> -o yaml
```

**Comment by kumachop2** [comment]
@harshit-splunk  I believe you're looking for daemonset yaml. Please confirm. 
Yes to address Azure Defender issue both migrate-checkpoint and patch-log-dirs  containers changed to  runAsUser to 20000 rather 0. Please confirm.

**Comment by kumachop2** [comment]
@harshit-splunk would you please provide update here.

**Comment by harshit-splunk** [comment]
Hi @kumachop2, sorry for the delay. I am not working with Splunk anymore 🙂
To answer your question, I was looking for daemonset instead of the deployment.

You need to run the init container as the root user, there is no work around for that. Log files belongs to the root user and the root group. To read the logs, your user should be either the root user or your user needs to be added to ACL with read permission. It also requires root privileges to add ACLs. I hope it answers your question.

**Comment by kumachop2** [comment]
@harshit-splunk  Thank You for the details and All the best for your future endeavor !!!

@atoulme I'll revert the runAsUser work around changes in   daemonset template and proceed with deploy the helm v0.70.0. Will keep you posted.

**Comment by kumachop2** [comment]
@atoulme  I did deployed helm v0.70.0 and without any  daemonset template changes ( Initi container running as root). After the deployment defender had reported "Running containers as root user should be avoided" recommendations. Here is values.yaml details and advice next steps. 
agent:
  enabled: true      
  securityContext:
    allowPrivilegeEscalation: false
    runAsUser: 20000
    runAsGroup: 20000

**Comment by atoulme** [comment]
This is a separate issue - please open a support case with us and we can try to look into it, but this is no longer the original issue reported.
