### ISSUE TITLE
Feature Request: Add automatic documentation creation from the values.yaml file

### ISSUE THREAD

**Issue by jvoravong** [signalfx/splunk-otel-collector-chart#659]
It would be great if customers could use a README.md file to understand how to use this chart instead of parsing the huge values.yaml file for this information.

Recommended Tool: https://github.com/norwoodj/helm-docs

Work Needed: Most of the comments in the values.yaml file would have to be refactored into a particular format.

Benefits: We'd have some easily digestable documentation for users.

**Comment by atoulme** [comment]
We will file this as an internal enhancement and work with our technical writer team to host the docs.
