### ISSUE TITLE
Namespace?

### ISSUE THREAD

**Issue by egkelly** [signalfx/splunk-otel-collector-chart#664]
Why is the collector chart not namespaced? Is there a reason, or is this an oversight?

**Comment by matthewmodestino** [comment]
You can namespace it by using the `-n foo` flag in your helm deployment...

I do it like this:

```helm -n otel install <your-clusterName> -f values.yaml splunk-otel-collector-chart/splunk-otel-collector```

I believe this is intended as we dont want to force a namespace on users for flexibility.

**Comment by matthewmodestino** [comment]
could be a good add to the getting started install docs just to call it out
