### ISSUE TITLE
Inefficient log filtering by annotations

### ISSUE THREAD

**Issue by dmitrykruglov** [signalfx/splunk-otel-collector-chart#666]
Hello, 

We are relying on the helm chart's `useSplunkIncludeAnnotation: true` feature to only forward the logs from the pods annotated with `splunk.com/include: true` annotation. 

Although the filtering works, we discovered that logs from non-annotated pods are still being processed in the log processing pipeline, where they are internally decorated and filtered, which can result in high CPU usage for no benefit (as those logs are just being discarded). This really starts to become a problem (high CPU usage and throttling) with the pods that are producing large amount of logs, like tens of thousands of log records per second. 

In our K8s clusters, currently we are mitigating this problem by manually excluding such pods from the pipeline entirely by using the helm chart's `logsCollection.containers.excludePaths` config. This helps us keep CPU usage low, but requires us to manually maintain a list of pods that need to be excluded.

It would be great if the helm chart's annotation log filtering feature could be enhanced so that logs from non-annotated pods wouldn't be processed and wouldn't affect resource usage.

**Comment by matthewmodestino** [comment]
This is where this old issue stemmed from as well, provides an example of overriding the default input

https://github.com/signalfx/splunk-otel-collector-chart/issues/395

**Comment by benoittoulme** [comment]
If I understood correctly, you are proposing to modify the otel config to set an include list there.

But that list will be static and have to be maintained. 
It seems to us it would be much easier to use the pod annotations to generate that list dynamically, we would not have to redeploy otel each time a new pod is being added to the cluster.

This is why we currently use an exclude list at the moment; we have to work with the otel config to filter out logs, but we cannot afford to redeploy otel all the time, so an include list does not really meet our needs in the context of a static, centralized config.

**Comment by matthewmodestino** [comment]
Yes, for the way the chart works today, having the include list is generally more managable and predictable than having to maintain an exclude list. In many cases, assuming naming conventions, or known logging targets, it can provide at least a better experience with less need to update. You would only ever need to update it if there was a new type of log that didnt fit ur existing glob definitions.

It definitely would be cool to have annotations somehow dynamically update the include list, no doubt. Just advising what might be better today while an enhancement like proposed would be looked at

**Comment by dmitrykruglov** [comment]
Thanks for your suggestion. However, maintaining an include list would not be a sustainable solution for our use case. We are trying to collect Docker logs from the Kubernetes nodes, and since the file paths for these logs look like "/var/log/pods/<namespace_name>_<pod_name>_<pod_uid>/<container_name>/<restart_count>.log", we would have to update the list every time a namespace or a pod is added, which happens frequently. This would require us to make very frequent deployments of splunk-otel-collector, which is not practical for us.

Regarding the CPU usage issue, we have observed that just one pod writing 20,000 log records per second consumes about 0.5 CPU, and causes CPU throttling on that pod. As splunk-otel-collector runs as a daemonset, if we were to trade off some efficiency for convenience to still allow for filtering this pod's logs by `[splunk.com/include`](http://splunk.com/include%60) annotation, we would have to allocate 0.5 CPU more to the daemonset. In a Kubernetes cluster with 30 nodes, this means we would be wasting 15 CPUs just to prevent throttling caused by that one pod. That's why relying solely on the `[splunk.com/include`](http://splunk.com/include%60) annotation filtering with the current implementation becomes very expensive at scale.

**Comment by matthewmodestino** [comment]
Thanks for the details! Helps to give the Eng team context.


But yeah, point taken, as an enhancement would be cool to have a dynamic way to update the include list based on annotations.

Until then the only way to manage the usage is via the options mentioned and I still maintain whatever logic being used for exclude, wouldnt be as good as thoughtful glob patterns on include. We have many customer doing precisely that today, or just adding the extra processing power. 

Look forward to any possible enhancements the team can come up with...

**Comment by benoittoulme** [comment]
We are mostly reactive right now - seeing CPU throttling on an agent, trying to understand which pod is causing the throttling, asking the dev team if possible to reduce docker logs and/or eventually exclude the pod from the otel ingest if not necessary.

But we want devs to be able to make their own decisions on which pod should get its docker logs ingested. There is no advantage for us to be gatekeepers and in the middle, managing a centralized include or exclude list. of course they are accountable and we can intervene if they log too much.

We will consider upping the limit short term, yes. We already did some of that. Thanks for considering this and for the doc.

**Comment by dmitrykruglov** [comment]
We agree that using include list is a better and more efficient approach, but we just cannot use it without having an automated solution for maintaining it. This is because manual maintenance of the list would be labor-intensive and require frequent deployments. That's why we would love to have a way to update the include list based on annotations, and we'll probably have to rely on the exclusion list until then, just because it requires fewer regular updates/deployments. We've been mostly excluding pods that are producing a large volume of low value logs, triggering `CPUThrottlingHigh` Prometheus alerts for splunk-otel-collector. 

> Guidance is 1 cpu 2Gi of ram for every 10k eps, as a note on existing guidance/expectations

Yes, we are familiar with the sizing guidance, it is reasonable for the events that should be part of the events processing pipelines, that could be potentially forwarded to Splunk.
However the issue is that, with the `[splunk.com/include`](http://splunk.com/include%60) annotation filtering, even the events that 100% should be discarded, still do consume the CPU/memory resources. We are pointing out this issue because it isn't a fundamental algorithmic performance issue, but rather a purely config management one, and if fixed, would make splunk-otel-collector deployments on Kubernetes much more efficient and reliable.

> I assume upping the limits on the daemonset doesnt necessarily mean itll use that extra resources on all nodes either, right? 

Yes, but it is important to note, that upping the `limits` on the daemonset is not a good and durable solution, it doesn't actually guarantee that splunk-otel-collector would be able to use those resources.
In order to guarantee that the agent can function properly and that we do not lose any important logs and metrics from any node, we would need to increase the resources `requests` on the daemonset, not the `limits`. This would make those resources unavailable to other workloads running on each node, and thus would waste resources if they are underutilized by splunk-otel-collector.

**Comment by matthewmodestino** [comment]
Thanks so much team! I have tossed it around internally to get eyes on it. Appreciate you sharing! Would totally be an awesome feature!

**Comment by matthewmodestino** [comment]
Yep, the only realistic thing I could imagine in future is a otel operator, that can dynamically update the filelog configs on the fly...i BELIEVE the otel agent can dynamically refresh its config, right? Or does it require a restart of the binary?

**Comment by dmitryax** [comment]
> Yep, the only realistic thing I could imagine in future is a otel operator, that can dynamically update the filelog configs on the fly.

Right, this type of work would be better handled by the operator.

> i BELIEVE the otel agent can dynamically refresh its config, right? Or does it require a restart of the binary?

Config change does require restart because it can affect the pipelines that need to be recreated.

**Comment by vihas-splunk** [comment]
Yeah, I'm thinking to add a new operator in https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/pkg/stanza/operator/input, or updating the file operator.
The new operator would take care of k8s.

**Comment by vihas-splunk** [comment]
If required, we can introduce k8s to the file input operator and it can update the `include` glob dynamically.
Because filelogreceiver uses`include` config every poll cycle and finds new matches. I think we can update that setting dynamically. But the effect will only be seen in subsequent poll cycles.
Other config changes requires a restart, as @dmitryax mentioned

**Comment by VihasMakwana** [comment]
How should we proceed on this @dmitryax @matthewmodestino ?

**Comment by dmitryax** [comment]
I don't think we should bring k8s metadata to filereceiver:
1. It brings a lot of complications and breaks the separation of concerns
2. It will utilize more memory and may be less CPU efficient than expected.

**Comment by matthewmodestino** [comment]
> I don't think we should bring k8s metadata to filereceiver:
> 
> 1. It brings a lot of complications and breaks the separation of concerns
> 
> 2. It will utilize more memory and may be less CPU efficient than expected.

I mostly agree, however will point out that because the kubelet adds most of the important metadata to the file path (namespace, pod name), we could likely get mostly there by only leveraging the metadata we already have in the source path. 

I still think the main item is having a watcher that can translate annotations to update the include/exclude dynamically, vs needing to change the filelog receiver all that much.

**Comment by atoulme** [comment]
We are closing issues and moving to track such enhancements through Splunk Ideas. I have filed an idea on your behalf, please see https://ideas.splunk.com/ideas/SFXIMMID-I-568
