### ISSUE TITLE
Enable ability to add prometheus scrape config from values.yaml

### ISSUE THREAD

**Issue by egkelly** [signalfx/splunk-otel-collector-chart#677]
Currently, I have to override the entire agent and collector configmaps to inject my own prometheus scrape config (I am installing this helm chart via terraform). It would be extremely useful to set a custom scrape config via helm values.

**Comment by atoulme** [comment]
Please flag this enhancement to your local Splunk rep and consider [opening a Splunk idea](https://ideas.splunk.com) if this is still relevant.
