### ISSUE TITLE
splunkPlatform.fieldNameConvention.renameFieldsSck doesn't cover journald units or extraFileLogs

### ISSUE THREAD

**Issue by vinzent** [signalfx/splunk-otel-collector-chart#682]
According to the SCK migration guide, it's possible to preserve the Splunk field names as used with SCK. Without this, we would need to rework all our custom Splunk Dashboards. 

https://github.com/signalfx/splunk-otel-collector-chart/blob/ff1e1ff2bf415ab8c7f37e03d85c056debf688b8/docs/migration-from-sck.md?plain=1#L405-L414

Now I discovered that the setting only affects the `logs` pipeline but not the `logs/host`. The `resource/logs` is not included in the `logs/host` pipeline. https://github.com/signalfx/splunk-otel-collector-chart/blob/ff1e1ff2bf415ab8c7f37e03d85c056debf688b8/helm-charts/splunk-otel-collector/templates/config/_otel-agent.tpl#L678

Probably for journald and extraFileLogs only the `cluster_name` field is relevant.

https://github.com/signalfx/splunk-otel-collector-chart/blob/ff1e1ff2bf415ab8c7f37e03d85c056debf688b8/helm-charts/splunk-otel-collector/templates/config/_common.tpl#L121-L123

**Comment by matthewmodestino** [comment]
I don't believe SCK really set any major fields for those sources...do you have examples of said fields? 
Most of them would have been custom, and can be set in otel anyways...

also while i understand it makes cutting over easy, SCK wasn't exactly thinking long term about fields and formats, where as OTel formats will be with us for the forseable future and beyond and in many cases has much better fields/info. so I'd caution staying married to anything SCK for the long term anyways....

**Comment by matthewmodestino** [comment]
Ah yes, will check the pipeline that gets made for extraFilelogs, I was playing with this backward compatibility feature recently. Worst case I should be able to see what needs to be added to the filelog and journald pipeline to add it.
