### ISSUE TITLE
What is the timeline on removing BETA tag

### ISSUE THREAD

**Issue by zaafar** [signalfx/splunk-otel-collector-chart#694]
Is there any plan/timeline/release version where the BETA tag is planned to be removed?

**Comment by matthewmodestino** [comment]
I too would like to see it removed as the BETA tag is not specific to Splunk Support. This chart is fully covered under Splunk SLAs and is ready for use. 

The Beta designation is in the context of the OpenTelemetry project as a whole and simply denotes there will be breaking changes across versions. 

See this note:
https://github.com/signalfx/splunk-otel-collector#current-status

You can and should feel comfortable using the chart. many of our customers do and it is THE solution for k8s collection for Splunk and is supported and ready to go.
