### ISSUE TITLE
Security Context is set on Windows Nodes

### ISSUE THREAD

**Issue by lftroyer** [signalfx/splunk-otel-collector-chart#704]
Similar to the following issue, runasuser: 0 is configured in the replicaset that gets deployed on windows nodes.  This causes a container start failure.  
https://github.com/aws/aws-node-termination-handler/issues/595
Also, isWindows: true does not create the necessary Node Selectors to ensure the pods are scheduled on Windows nodes.
nodeSelector: 
  kubernetes.io/os: windows
  kubernetes.io/arch: amd64

**Comment by jvoravong** [comment]
- isWindows does set the n[ode selector "kubernetes.io/os: windows"](https://github.com/jvoravong/splunk-otel-collector-chart/blob/38c6a385ba1588cca10081b6065a2fe3929e2052/examples/kubernetes-windows-nodes/rendered_manifests/daemonset.yaml#L39).
- Have you tried configuring [agent.securityContext](https://github.com/signalfx/splunk-otel-collector-chart/blob/a0da502f1a845433ace335bc792dfc4b371eac08/helm-charts/splunk-otel-collector/values.yaml#L367) to modify the runAsUser value?
