### ISSUE TITLE
Dashboards for basic Kubernetes monitoring 

### ISSUE THREAD

**Issue by naveen-goswami** [signalfx/splunk-otel-collector-chart#705]
We are running Splunk Enterprise, It'd be really great to have Kubernetes basic monitoring dashboard's XML files in this repo. Moreover, I am new to the whole Splunk ecosystem any recommendation would be much appreciated to setup basic monitoring dashboards for Kubernetes.

**Comment by matthewmodestino** [comment]
Hey, 

A few of us Splunkers are working on it now that we have OTel here for the long run. 

you can come [join us in the community slack channel ](splk.it/slack)to keep up to date on what we come up with or to share ideas on what you's like to see. 

Come fine me in the Kubernetes room. username is mattymo. 

For now, you would need to build your own.

**Comment by atoulme** [comment]
Please also consider a [Splunk Idea](https://ideas.splunk.com) to implement this.
