### ISSUE TITLE
Inconsistent metric names

### ISSUE THREAD

**Issue by M-Bates** [signalfx/splunk-otel-collector-chart#706]
I have noticed that this collector/exporter is creating metrics in Splunk with 2 different metric names for the same object (no overlap in metric data points).

This is only occurring for container level metrics.

container.cpu.utilization
vs
k8s.container.cpu.limit

![image](https://user-images.githubusercontent.com/87510651/226799803-75f91624-128f-404e-a2fc-3a71377a52b1.png)

**Comment by dmitryax** [comment]
The naming is expected as it's currently defined in OTel. `container.cpu.utilization` is not attached to any particular container orchestration platform, while `k8s.container.cpu.limit` is taken from the pod spec which is a k8s concept.

**Comment by M-Bates** [comment]
Thanks, but then why is this still not standard as pods and node are under k8s.
It is only container that is seems to be inconsistent.

container.cpu.utilization
vs
k8s.pod.cpu.utilization

**Comment by dmitryax** [comment]
> Thanks, but then why is this still not standard as pods and node are under k8s.

Because pod and node are k8s concepts, container is not.

**Comment by dmitryax** [comment]
If you think it's wrong, feel free to submit an issue in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues against `receiver/kubeletstats` component to involve the OpenTelemetry community in the discussion.

**Comment by atoulme** [comment]
Closing this issue as answered.
