### ISSUE TITLE
Unable to install with splunkObservability properties disabled

### ISSUE THREAD

**Issue by srisujan** [signalfx/splunk-otel-collector-chart#722]
We are trying to migrate from splunk-connect-for.kubernetes to splunk-otel-collector.

Our configuration is like, logs will be sent to splunk cloud and metrics will be sent to signalFX.
When we try to set splunkObservability.logs/metrics/traces/profiling set to false. the helm upgrade fails with the following error message

*****************************
Error: UPGRADE FAILED: values don't meet the specifications of the schema(s) in the following chart(s):
splunk-otel-collector:
- splunkObservability: Must validate at least one schema (anyOf)
- splunkObservability.metricsEnabled: splunkObservability.metricsEnabled does not match: true

##[error]Error: UPGRADE FAILED: values don't meet the specifications of the schema(s) in the following chart(s):
splunk-otel-collector:
- splunkObservability: Must validate at least one schema (anyOf)
- splunkObservability.metricsEnabled: splunkObservability.metricsEnabled does not match: true
 *************************************************

We could see the condition in schema as below:
![image](https://user-images.githubusercontent.com/24322019/231127195-8e37b7c8-0fe6-432a-bdce-c29e1f61e1cd.png)
That forces us to set any of these to true. But we dont want to enable metrics in lower environments or rather make it to selective environments but production.

Please advise

**Comment by atoulme** [comment]
I'm not sure I follow. Please attach your values.yaml for reproduction (remove any tokens and URLs please). Alternatively, please open a support case.

**Comment by srisujan** [comment]
Support Case: CASE [3201437] 

Attaching the values.yaml generated without any sensitive data here.

We are trying to achieve the following
SplunkPlatform - connects to splunk cloud and export only the logs
SplunkObservability connects to SignalFX realm to send only metrics

In lower environments we dont want to send metrics to SignalFX But only in performance and prod envrionments

In dev environment when we set logsEnabled to true in SplunkPlatform and set everything else to false. And in SplunkObservability we set traces to true and rest everything to false.. We get error and the PODs get CrashLoopBackOff

**Comment by srisujan** [comment]
While on the SplunkPlatform section
![image](https://user-images.githubusercontent.com/24322019/232461897-8c5ee3d1-82ef-4a8f-87ca-3857a30d21ef.png)

**Comment by srisujan** [comment]
[0.72.0-values.zip](https://github.com/signalfx/splunk-otel-collector-chart/files/11249168/0.72.0-values.zip)

**Comment by matthewmodestino** [comment]
When you run into this issue, are you leaving the token/realm for o11y in the config then setting metrics to false? Can you try and remove the realm and token in the environments you don't want to send the metrics in?

You also said you are working with metrics then advise you are enabling traces? So are you trying to send traces and not metrics to o11y in the lower environments?

**Comment by srisujan** [comment]
Ok that is the exact problem. We did raise a supportCase for the same. Not sure if we have to run both. But what you @matthewmodestino  mentioned is the exact problem.

Ideally, We want to enable logs across all our environments and when it comes to metrics, We would like to enable it in specific environments only, We are sending logs to Splunk Cloud and metrics to SignalFX. 

When we try to disable all metrics configurations to FALSE including logs, metrics and traces. The helm deployment of splunk-otel-collector fails, as the schema mandates atleast one of the properties to be set to TRUE. So we are forced to set traces to TRUE and metrics to FALSE. But then we are getting other problem as mentioned above.

But please refer / link to SupportCase:  Case #3201437 Issue with oTel configurations [ ref:_00D409oyL._5005a2T6rqx:ref ]

**Comment by srisujan** [comment]
We did try disabling REALM But it doesnt make any effect on the schema validation

**Comment by atoulme** [comment]
Thanks for filing a support case. Please follow up through the support case for further help. Closing.
