### ISSUE TITLE
Expose idle_conn_timeout in the helm chart values

### ISSUE THREAD

**Issue by atoulme** [signalfx/splunk-otel-collector-chart#725]
See https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/20543 for context. We need to expose this as a new flag in values.yaml.

**Comment by atoulme** [comment]
Now fixed with #728

**Comment by suresh0204** [comment]
Error: UPGRADE FAILED: values don't meet the specifications of the schema(s) in the following chart(s):
splunk-otel-collector:
- splunkPlatform: Additional property idleConnTimeout is not allowed

We are seeing this error when trying to upgrade.

**Comment by atoulme** [comment]
I have opened #733 to follow up.
