### ISSUE TITLE
With logsEngine: fluentd the multiline works fine and when it is set to otel the multiline breaks 

### ISSUE THREAD

**Issue by suresh0204** [signalfx/splunk-otel-collector-chart#727]
The multiline block that works with logsEngine: fluentd, it does not work when logsEngine is changed to otel in values.yaml configuration.

The app version we are using is 0.72.0

**Comment by atoulme** [comment]
Please provide the values.yaml used.

**Comment by suresh0204** [comment]
[values.txt](https://github.com/signalfx/splunk-otel-collector-chart/files/11216852/values.txt)
In the file I have given the sample multiline block as below

      <pod_name>:
        from:
          pod: <pod_name>
          container: <container_name>
        timestampExtraction:
          regexp: (?<time>\d{4}-\d{2}-\d{2} [0-2]\d:[0-5]\d:[0-5]\d\.\d{3})
          format: "%Y-%m-%d %H:%M:%S.%3N"
        multiline:
          firstline: /^\d{4}-\d{2}-\d{2} [0-2]\d:[0-5]\d:[0-5]\d\.\d{3}/
        sourcetype: kube:container:<container_name>

**Comment by atoulme** [comment]
Sure, please look here: https://github.com/signalfx/splunk-otel-collector-chart/blob/main/docs/advanced-configuration.md#processing-multi-line-logs

**Comment by atoulme** [comment]
Closing as answered, please comment if more work is needed.
