### ISSUE TITLE
Otel agent doesn't start in the gateway (otelCollector.enabled=true) mode

### ISSUE THREAD

**Issue by dmitryax** [signalfx/splunk-otel-collector-chart#73]
Use the following helm values:
```
<hidden required fields>

otelCollector:
  enabled: true
```

Collector running as agent is failing with the following message:
```
Error: cannot load configuration: pipeline "traces" references exporter "signalfx" which does not exist
2021/03/24 16:00:04 main.go:74: application run finished with error: cannot load configuration: pipeline "traces" references exporter "signalfx" which does not exist
```

**Comment by jrcamp** [comment]
Hmm I think signalfx should probably not be in the trace pipeline in the gateway mode since it's only for correlation which has to run on the agent only.

**Comment by dmitryax** [comment]
@jrcamp can we utilize https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/httpforwarder to make correlation work in the gateway mode?

**Comment by jrcamp** [comment]
Yep I think so
