### ISSUE TITLE
Error: UPGRADE FAILED: values don't meet the specifications of the schema(s) in the following chart(s):

### ISSUE THREAD

**Issue by atoulme** [signalfx/splunk-otel-collector-chart#733]
Error: UPGRADE FAILED: values don't meet the specifications of the schema(s) in the following chart(s):
splunk-otel-collector:
- splunkPlatform: Additional property idleConnTimeout is not allowed

We are seeing this error when trying to upgrade.

_Originally posted by @suresh0204 in https://github.com/signalfx/splunk-otel-collector-chart/issues/725#issuecomment-1507331610_

**Comment by atoulme** [comment]
@suresh0204 it might be best to first upgrade then apply separately, adding this new setting in your values.yaml. Please try and let us know if that helps.

**Comment by atoulme** [comment]
Please report if my instructions above helped @suresh0204 - I plan to close this issue by end of week if I don't hear back.

**Comment by matthewmodestino** [comment]
I always advise users to follow these steps when upgrading:

- upgrade the local chart

```
Helm repo update splunk-otel-collector-chart
```

- Create a new base values.yaml from the new chart release

```
helm show values splunk-otel-collector-chart/splunk-otel-collector > values.yaml
```

- Copy in your changes to the new base values file then upgrade

```
helm -n otel upgrade <your helm deployment> -f values.yaml splunk-otel-collector-chart/splunk-otel-collector
```

You can get your helm deployment using `helm ls -n foo`

These steps ensure you aren't using an old chart or values schema with an updated version that has changes.

Let us know if this helps get you sorted.

**Comment by atoulme** [comment]
I assume this is resolved. Please reopen if more work is needed.
