### ISSUE TITLE
Add labels and service entry

### ISSUE THREAD

**Issue by mr-miles** [signalfx/splunk-otel-collector-chart#741]
### Is your feature request related to a problem? Please describe.

I have a process running on each node and I want it to send requests to the node-local agent trace endpoints.  I don't have any way to configure it on a node-specific basis - it can only be configured via config file and that has to be the same everywhere.

I planned to do this by defining a service that points to the pods in the daemonset and has a local InternalTrafficPolicy.  This would mean traffic always targetted the node-local endpoints.

It works very well but I found the pods in the daemonset are missing a label to enable them to be targetted by a selector.

### Describe the solution you'd like

I made a PR that adds the component label and also an option to the chart that sets up a service entry as described.
https://github.com/signalfx/splunk-otel-collector-chart/pull/740

**Comment by atoulme** [comment]
Thank you for your contribution! Closing this issue as complete.
