### ISSUE TITLE
Failed to send metrics: Unable to send datapoints post Helm v0.75.0 upgrade

### ISSUE THREAD

**Issue by kumachop2** [signalfx/splunk-otel-collector-chart#766]
Unable to send datapoints post Helm v0.75.0 upgrade. 

I have updated Splunk helm from v0.72.0 to v0.75.0 and getting flood of warning messages mentioned below. Please do let me know 

[otel.javaagent 2023-04-25 22:23:30:008 +0000] [signalfx-metrics-publisher] WARN com.splunk.javaagent.shaded.io.micrometer.signalfx.SignalFxMeterRegistry - failed to send metrics: Unable to send datapoints

Env: AKS
Splunk Helm: v0.75.0
Splunk Otel JAVA SDK: 1.17

Here is Java containers configuration: and flood of message started post upgrade of Helm v0.75.0 only. Also no issues with Splunk Agents.

SPLUNK_PROFILER_DIRECTORY=/tmp
SPLUNK_OTEL_AGENT=*.*.*.63
SPLUNK_PROFILER_MEMORY_ENABLED=true
SPLUNK_METRICS_ENABLED=true
SPLUNK_METRICS_ENDPOINT=http://*.*.*.63:9943
SPLUNK_PROFILER_ENABLED=true

**Comment by kumachop2** [comment]
I found the cause and applied the changes

**Comment by sathishrpt24** [comment]
Hi @kumachop2 , What is fix you have provided? we are facing similar issues and our logs are loaded with warning with above message you have specified

**Comment by atoulme** [comment]
Thank you for your report, please file a support ticket to receive timely help: https://splunk.my.site.com/customer/s/need-help/create-case
