### ISSUE TITLE
AWS EKS NodeGroup Information

### ISSUE THREAD

**Issue by fwesselhoft** [signalfx/splunk-otel-collector-chart#776]
### Describe the issue you're reporting

Hi! We have recently started using the Splunk Otel chart to send our data to Splunk, after a bit of trial/error everything seems to working alright; nevertheless, we are struggling a bit trying to find what is the best way to bring NodeGroup information to the events/metrics. Currently I see bunch of metrics for nodes, pod, system, daemonset and so forth, but nothing in regards to the nodeGroups.

We are using AWS EKS, and we have several nodeGroups running in the same cluster; hence, it'd be great to have an easy way to get metrics based on the nodeGroup itself, or at least a way to map the single_nodes to the parent nodeGroup. 

I would appreciate any pointers, thank you! 

Fritz

**Comment by atoulme** [comment]
Thank you for your suggestion. I have captured your feedback in https://ideas.splunk.com/ideas/SFXIMMID-I-551 and we will continue to track it there. Please feel free to upvote the idea to give it more visibility.
