### ISSUE TITLE
Add service.name attribute automatically when logsEngine=otel and autodetect.istio=true

### ISSUE THREAD

**Issue by apaska-splunk** [signalfx/splunk-otel-collector-chart#777]
### Is your feature request related to a problem? Please describe.

We need the `service.name` attribute to be created automatically for istio logs when setting `logsEngine: otel` and `autodetect.istio=true`. This is a known limitation per the [advanced configs docs](https://github.com/signalfx/splunk-otel-collector-chart/blob/main/docs/advanced-configuration.md#logs-collection) and prevents an easy path to deploying the collector without fluentd while also having istio correlation between cloud and o11y.

### Describe the solution you'd like

I'd like to see this functionality added so that we do not have to choose between otel scalability and istio correlation.

### Describe alternatives you've considered

I will try to manipulate the pipeline manually to add that attribute

**Comment by dmitryax** [comment]
Resolved by https://github.com/signalfx/splunk-otel-collector-chart/pull/825
