### ISSUE TITLE
Support multiline config from pod annotations

### ISSUE THREAD

**Issue by sylr** [signalfx/splunk-otel-collector-chart#778]
Hi,

It would be really helpful if we could configure multiline configuration from pod annotations like [outcoldsolutions kubernetes collector allows to](https://www.outcoldsolutions.com/docs/monitoring-kubernetes/v5/annotations/).

Regards.

**Comment by sylr** [comment]
@atoulme why did you transfer this issue to `signalfx/splunk-otel-collector-chart` ? Unless I missed it and it is already implemented, this is something that has to be done in the collector itself.

**Comment by omrozowicz-splunk** [comment]
Hey, just to make sure we're on the same page. You mean the feature to be able to set multiline config regex as a pod annotation? So then you process logs depending on config per pod based on whatever was set up in the annotation?
I think you're right there's nothing like that in `signalfx/splunk-otel-collector` repo, but such a change would require work on `signalfx/splunk-otel-collector-chart` as well.

**Comment by sylr** [comment]
> I think you're right there's nothing like that in signalfx/splunk-otel-collector

No there isn't, that why this issue was created in https://github.com/signalfx/splunk-otel-collector, where it should be implemented.

**Comment by atoulme** [comment]
Sorry, the reason I moved this to the chart is because this needs to be prioritized by the team responsible for log collection. Right now, there isn't a good way to make this change and it needs to be prioritized. I have opened a Splunk idea to follow up: https://ideas.splunk.com/ideas/EID-I-2100
