### ISSUE TITLE
Duplicate events in Splunk - aligns with context deadline exceeded (Client.Timeout exceeded while awaiting headers) error timeline

### ISSUE THREAD

**Issue by dbhojani** [signalfx/splunk-otel-collector-chart#779]
## Description
We are seeing duplicate events in Splunk.

**logging method** : GKE container logs > otel > Splunk cloud  via HEC
Otel Version : 0.70.0

**Updates made so far but no luck**

- Increased queue size for HEC inputs to reduce server errors
- Upgraded Otel Collector to 0.70.0 ( few months back )
- Increased timeout to 20s  on Otel collector
- Upgraded Splunk Cloud to latest version 9

We are seeing a lot of "exporting failed", context deadline exceeded. These errors aligns with our duplicate events timeline in Splunk. PFA.

2023-05-07T04:38:43.999Z	info	exporterhelper/queued_retry.go:426	Exporting failed. Will retry the request after interval.	{"kind": "exporter", "data_type": "logs", "name": "splunk_hec/platform_logs", "error": "Post \"https://<STACKNAME>.splunkcloud.com/services/collector\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)", "interval": "6.098075932s"}

## Expected Result
No duplicates in Splunk

## Actual Result
Many duplicates in Splunk, specially when indexer cluster going under rolling-restart

![Timeout- Otel errors](https://user-images.githubusercontent.com/122061937/236872421-93ea2006-e78e-45d2-a25b-d6340946dced.png)

**Comment by VihasMakwana** [comment]
@dbhojani is the splunk hec healthy? have you noticed anything strange in splunkd logs? The exporter is saying that HEC is not responding

**Comment by dbhojani** [comment]
@VihasMakwana We have very large environment with 135 indexers and 40+ TB of day per day. So it could be possible that sometimes it become unresponsive throwing "server busy error" , we did work with Splunk support & they suggested increasing HEC queue size, that we already did few weeks back. That has reduced the "server busy errors" in internal logs. However, specially during cluster restarts , we are still getting some "server error" when HEC is busy. 

My concern is, we get duplicate events which aligns time same time when we get "client timeout" in otel logs ?

**Comment by VihasMakwana** [comment]
> @VihasMakwana
> 
> Thanks for the quick response.
> 
> We have very large environment with 135 indexers and 40+ TB of data per day. So it could be possible that sometimes it become unresponsive throwing "server busy error" , we did work with Splunk support & they suggested increasing HEC queue size, that we already did few weeks back. That has reduced the "server busy errors" in internal logs. However, specially during cluster restarts , we are still getting some "server error" when HEC is busy.
> 
> We have had timeout settings updated to 20s in Otel configurations as per Splunk team's suggestion.
> 
> My concern is, we get duplicate events which aligns time same time when we get "client timeout" in Otel logs ? Could this be a bug ?

Maybe, I'm looking for any bugs right now, are you using default values.yaml?

**Comment by dbhojani** [comment]
Sorry for the delay.
Yes, most configs are default. We do have some index based routing configured but nothing specific other than that.
Also, we recently upgrade otel to 0.76.0 version but no luck. Don't see much improvement in duplicates.

**Comment by kishah-lilly** [comment]
We are seeing the same on ROSA version 4.13.

On the agent pods:
> 2023-06-13T17:41:01.990Z error prometheusexporter/prometheus.go:139 Could not get prometheus metrics {"kind": "receiver", "name": "receiver_creator", "data_type": "metrics", "name": "smartagent/coredns/receiver_creator{endpoint=\"[REDACTED]\"}/k8s_observer/720f4fee-c514-4900-9ffc-e302508f85a4", "error": "Get \"https://[REDACTED]/metrics\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)", "monitorID": "smartagentcorednsreceiver_creatorendpoint[REDACTED]k8s_observer720f4feec51449009ffce302508f85a4", "monitorType": "coredns"}

On the cluster receiver pod:
> 2023-06-13T17:39:31.664Z error dimensions/dimclient.go:246 Unable to update dimension, retrying {"kind": "exporter", "data_type": "metrics", "name": "signalfx", "error": "error making HTTP request to https://api.[REDACTED].signalfx.com/v2/dimension/container.id/[REDACTED]/_/sfxagent: Patch \"https://api.[REDACTED].signalfx.com/v2/dimension/container.id/[REDACTED]/_/sfxagent\": net/http: invalid header field value for \"X-Sf-Token\"", "URL": "https://api.[REDACTED].signalfx.com/v2/dimension/container.id/[REDACTED]/_/sfxagent", "dimensionUpdate": "{name: \"container.id\"; value: \"[REDACTED]\"; props: {container.status: \"running\"}; tags: map[]}", "statusCode": 0}
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/signalfxexporter/internal/dimensions.(*DimensionClient).handleDimensionUpdate.func1

**Comment by VihasMakwana** [comment]
@dbhojani I don't feel like this is a bug, the error `context deadline exceeded (Client.Timeout exceeded while awaiting headers)` seems to be related to with networking. 
I have a thing to confirm, is duplication correlated to `server error" when HEC is busy?`?

**Comment by dbhojani** [comment]
Is duplication correlated to server error" when HEC is busy??  -- Yes.

**Comment by VihasMakwana** [comment]
If the events are duplicated and you're not sending the same event twice then this seems like an issue with the server or network, could be anything. 
The above error means that the client i.e. our collector can't reach the server for whatever reason (DNS, firewall, etc)

**Comment by omrozowicz-splunk** [comment]
Hey @dbhojani can you check if these `duplicated events` are really the duplicated events or are they a little different based on its `_time`? My idea here is that sometimes events look like they're duplicated, but in fact they're a little bit different based on the time it originated. An example:

I run the query in Splunk to check the duplicated logs: `index=em* | stats count by _raw, index, sourcetype, source, host | where count>1`

And get some results:

<img width="1493" alt="image" src="https://github.com/signalfx/splunk-otel-collector-chart/assets/86965961/ed4f448d-9180-4e29-a2cb-f939a6c63f32">

They look like duplicates:
<img width="1198" alt="image" src="https://github.com/signalfx/splunk-otel-collector-chart/assets/86965961/807c6b1b-a391-4684-8837-12f99e1c37e9">

But in fact their timestamps are a little bit different:
```
splunker@i-0205459173e833a3f:~$ sudo cat /var/log/pods/kube-system_calico-node-rwtzd_17114d78-197d-40dd-a25d-1c1b37bf6756/calico-node/0.log | grep "2023-08-07 08:59:27.216" | grep "tunnel-ip-allocator/watchersyncer.go 209: Received InSync event from one of the watcher caches"
2023-08-07T08:59:27.217196627Z stdout F 2023-08-07 08:59:27.216 [INFO][80] tunnel-ip-allocator/watchersyncer.go 209: Received InSync event from one of the watcher caches
2023-08-07T08:59:27.217207676Z stdout F 2023-08-07 08:59:27.216 [INFO][80] tunnel-ip-allocator/watchersyncer.go 209: Received InSync event from one of the watcher caches
```

In splunk you can see it under `time` field:
<img width="489" alt="image" src="https://github.com/signalfx/splunk-otel-collector-chart/assets/86965961/5876786f-d5cb-46eb-ab46-4d2a1d14a898">
<img width="490" alt="image" src="https://github.com/signalfx/splunk-otel-collector-chart/assets/86965961/86b57b37-345f-4f7f-813a-19c73f1aa0fd">

Can you confirm this is not the case?

**Comment by atoulme** [comment]
@dbhojani please open a support case to follow up so we can engage with you. I am closing this issue as inactive.
