### ISSUE TITLE
Missing Index parameter on advanced configuration

### ISSUE THREAD

**Issue by iortiz-splunk** [signalfx/splunk-otel-collector-chart#782]
### Describe the issue you're reporting

The advanced documentation example for the [logsCollection](https://github.com/signalfx/splunk-otel-collector-chart/blob/main/docs/advanced-configuration.md#add-log-files-from-kubernetes-host-machinesvolumes) does not show the `com.splunk.index` parameter. This is confusing to users as they have no way of knowing that it is possible to send these logs to separate indexes

**Comment by atoulme** [comment]
Please see the official documentation here on how to use annotations to manage index routing: https://docs.splunk.com/observability/en/gdi/opentelemetry/kubernetes-config-logs.html#manage-log-ingestion-using-annotations
You can provide feedback on the page itself. I will also relay this feedback on the page now and will close this issue now.
