### ISSUE TITLE
Read AWS EC2 Tags

### ISSUE THREAD

**Issue by fwesselhoft** [signalfx/splunk-otel-collector-chart#787]
### Is your feature request related to a problem? Please describe.

Yes! We have AWS EKS and OTEL configured and working. Currently we are trying to leverage the OTEL metrics against multiple NodeGroups, in the same cluster. Nevertheless, on the current metric info we get, we don't see NodeGroup related details that could help us map if the NODE belongs to NodeGroupA, or B, or X.

### Describe the solution you'd like

I noticed by default EKS adds a tag "eks:nodegroup-name" to each EC2 node, and therefore, I am trying to see if there is a way we could read from the TAGS of the EC2 itself and incorporate those values to metrics and/or events, that would solve our requirement and it would allow folks to ingest all sort of important details as part of the EC2 tags.

### Describe alternatives you've considered

Manual mapping, or using Splunk to combine results from EKS with other queries that may already collect tags from EC2s, both ways are not ideal.

**Comment by omrozowicz-splunk** [comment]
Hey,
I am not aware of the full context of EKS/EC2 tags, but I can see in `resourcedetectionprocessor` that we use there is actually a tags option:
