### ISSUE TITLE
otel collector not able to send logs from volume path on AKS cluster

### ISSUE THREAD

**Issue by ramesh569** [signalfx/splunk-otel-collector-chart#794]
### Describe the issue you're reporting

Hi Team,

i am trying to setup otel agent to send AKS logs to splunk index.   Actually logs are mounted on /appl/server/log path. 

i have made below configuration in values.yml file 

under Agent section:

    extraVolumes: 
      - name: app-logs
        hostPath:
          path: /appl/server/log
    extraVolumeMounts:
      - name: app-logs
        mountPath: /appl/server/log

also added below config under log collection section

    extraFileLogs:
      filelog/app-logs:
        include: [/appl/server/log/*.log]
        start_at: beginning
        include_file_path: true
        include_file_name: true
        resource:
          com.splunk.source: /appl/server/log/*.log
          host.name: 'EXPR(env("K8S_NODE_NAME"))'
          com.splunk.sourcetype: applogs

i deployed helm charts on name space. but it does not sending any logs from this path to index, also don't see any errors in logs except below warning.

2023-05-22T08:18:25.106Z        warn    fileconsumer/file.go:63 no files match the configured include patterns  {"kind": "receiver", "name": "filelog", "data_type": "logs", "component": "fileconsumer", "include": ["/appl/server/log/*.log"],

am i missing anything here ? thanks in advance

**Comment by omrozowicz-splunk** [comment]
Hey,
Maybe this is a basic advice, but shouldn't the path be `/appl/server/logs/*.log`? Logs with `s` at the end? Because you mentioned 
> Actually logs are mounted on /appl/server/logs path

**Comment by ramesh569** [comment]
> Hey, Maybe this is a basic advice, but shouldn't the path be `/appl/server/logs/*.log`? Logs with `s` at the end? Because you mentioned
> 
> > Actually logs are mounted on /appl/server/logs path

logs are stored in /appl/server/logs  path. under this we have log files like application.log

**Comment by omrozowicz-splunk** [comment]
Ok, because in your config you have `include: [/appl/server/log/*.log]` everywhere, this seems like a different path. 
Can you update `/appl/server/log/*.log` to `/appl/server/logs/*.log` and `/appl/server/log` to `/appl/server/logs`?

**Comment by ramesh569** [comment]
> Ok, because in your config you have `include: [/appl/server/log/*.log]` everywhere, this seems like a different path. Can you update `/appl/server/log/*.log` to `/appl/server/logs/*.log` and `/appl/server/log` to `/appl/server/logs`?

sorry, its my bad,  actuall path is  /appl/server/log   which is actual path and configured same but logs are not forwarding to index

**Comment by omrozowicz-splunk** [comment]
I used your config and created a log following `/appl/server/log/*.log` pattern and it works correctly for me.
Are you sure you have any files in `/appl/server/log` on this node? You can additionally find out what files are visible from the otel collector pod perspective using command:
```
kubectl exec -it pod/my-splunk-otel-collector-agent-6ddjp -- ls /appl/server/log
```
Where `pod/my-splunk-otel-collector-agent-6ddjp ` is your agent pod name.

**Comment by ramesh569** [comment]
> 

I am not getting any data when i execute this command.    let me give you clear info 
pods are writing logs to /appl/ri****/server/log which is mounted on azure file share. 
when i connect to application pod and check the above path, i see log files exist.

![image](https://github.com/signalfx/splunk-otel-collector-chart/assets/29400228/ecd2c24a-be71-4eb1-9c38-7d8045299a97)


please find above screenshot how it looks inside app pod, may be i am adding  wrong configuration in values file.. 
i doubt that should i use /appl/ri***/server/log or //fileshare/*/logs path in values file.

thank you for your time

**Comment by omrozowicz-splunk** [comment]
> i doubt that should i use /appl/ri***/server/log or //fileshare/*/logs path in values file.

Why is that?
It looks like you should use `/appl/ri*/server/log` in include statement as this is the correct path in your system where you have logs (the mount place for your azure logs). Can you update all paths in the config with this value? Also, is `ri*` something dynamic that can be different depending on the node? Or you just added `*` for anonymization purposes?

**Comment by omrozowicz-splunk** [comment]
`include` statement works with `*`, but I don't think `mountPath` or `hostPath` support that. You need to provide the path explicitly there, or mount the whole `/appl` directory, like:

```
  extraVolumes: 
  - name: app-logs
    hostPath:
      path: /appl
 extraVolumeMounts:
  - name: app-logs
    mountPath: /appl
```

**Comment by ramesh569** [comment]
> `include` statement works with `*`, but I don't think `mountPath` or `hostPath` support that. You need to provide the path explicitly there, or mount the whole `/appl` directory, like:
> 
> ```
>   extraVolumes: 
>   - name: app-logs
>     hostPath:
>       path: /appl
>  extraVolumeMounts:
>   - name: app-logs
>     mountPath: /appl
> ```

i have provide complete path . in post i am mentioning * as  i dont want to disclose here:)

**Comment by omrozowicz-splunk** [comment]
Ah, okay. Sorry, didn't get it. Does it still not see any files?

**Comment by ramesh569** [comment]
> Ah, okay. Sorry, didn't get it. Does it still not see any files?

find something here , when i try to list the log directory, it says no files
![image](https://github.com/signalfx/splunk-otel-collector-chart/assets/29400228/2f710903-705f-492f-9d16-e1932fd6750b)
but actually there application logs.

should we change some recievers, exporters config changes in helm ?

**Comment by omrozowicz-splunk** [comment]
Hey,
I think `agent.securityContext` https://github.com/signalfx/splunk-otel-collector-chart/blob/7698ca2498dffe121ec7776227c4bf77733a1dba/helm-charts/splunk-otel-collector/values.yaml#L369 is the one, but it is already set up to be root by default, so permissions shouldn't be a problem I think

> i am able to list out directories upto log folder from /appl but not inside log folder.

You mean when you mounted hostPath as `/appl` directories are inside, but not logs at the end?


I'm starting to think that maybe the way it works differently on AKS in terms of how filesystem is being seen by the K8s system. Maybe I would try to create just a bare pod trying to mount any of those paths to see if it's even visible? I found some more complicated way of creating volume mounts in AKS here: https://learn.microsoft.com/en-us/azure/aks/azure-csi-files-storage-provision, I am not an AKS expert, but maybe it requires this settings to mount anything that is taken from `*file.core.windows.net`?

> donot see port 13133 in config anywhere ? how can i resolve this

This is a readiness probe of the otel collector pod itself, does it happen frequently? 
```
If a readiness probe fails, it indicates that the container is not yet in a ready state, and the orchestrator will consider the container as unavailable for serving traffic. This could be due to various reasons, such as the container taking longer than expected to start up, encountering an error during initialization, or being overwhelmed with existing workload and unable to handle additional requests.
```

**Comment by ramesh569** [comment]
it was my mistake, mount path is not on host machine. it is on Persistent Volume Claim, after i changing to PVC, it is able to sent logs to splunk. thanks
