### ISSUE TITLE
Refactor otel collector feature gate configs to be (startup) cmd configs

### ISSUE THREAD

**Issue by jvoravong** [signalfx/splunk-otel-collector-chart#812]
### Is your feature request related to a problem? Please describe.

Description:
It would be useful to have access to the otel collector startup cmd to toggle feature gates and add other arguments.

### Describe the solution you'd like

AC:
- Refactor the following configurations for[ feature gates](https://github.com/signalfx/splunk-otel-collector-chart/blob/6646f31acdcd43af680de70dcf514e26afd7ceab/helm-charts/splunk-otel-collector/values.yaml#LL398C3-L398C3) to be used for modifying the start up command of the collector.
  - agent.featureGates -> agent.otelcol.cmd?
  - cllusterReceiver.featureGates -> cllusterReceiver.otelcol.cmd?
  - gateway.featureGates -> gateway.otelcol.cmd?
- Update documentation and examples.

**Comment by dmitryax** [comment]
`agent.otelcol.cmdArgs` maybe?
