### ISSUE TITLE
Remove containerRuntime config

### ISSUE THREAD

**Issue by VihasMakwana** [signalfx/splunk-otel-collector-chart#829]
### Describe the issue you're reporting

The [containerRuntime](https://github.com/signalfx/splunk-otel-collector-chart/blob/main/helm-charts/splunk-otel-collector/values.yaml#L533) setting is used to route the incoming logs using expressions.
The collector works well if we keep this field blank, but we saw in [issue](https://github.com/signalfx/splunk-otel-collector-chart/issues/644) that if we change the timezone for contained runtime, it breaks our hardcoded logic.
The CRI-O and contained logs are similar, 
`<timestamp> <stdout|stderr> <logtag> <log message>`

The timestamp is of the `rfc3339Nano` specification. The PR [#817](https://github.com/signalfx/splunk-otel-collector-chart/pull/817) has updated the timestamp to rfc3339Nano.
I think we can keep two routers only and remove `containerRuntime` config:
- One for docker
- One for cri-o/containerd

**Comment by jvoravong** [comment]
Might be worth creating a related ticket in our sibling project https://github.com/open-telemetry/opentelemetry-helm-charts/tree/main/charts/opentelemetry-collector so we can influence the community and stay in sync where possible.

**Comment by VihasMakwana** [comment]
Sure, will do

**Comment by VihasMakwana** [comment]
Will work on rolling out PR by today.
