### ISSUE TITLE
OTEL Agents are duplicating data from shared mount paths on AKS cluster

### ISSUE THREAD

**Issue by ramesh569** [signalfx/splunk-otel-collector-chart#853]
Hi,

we have deployed otel agent as deamon set on aks cluster, we are disabled all default logs  and sending all logs from shared mount path. this mount path is shared across the cluster nodes.  agents on different host machine sending same logs data from the mount path. 
 
in configuration we have added the shared mount path as extra volume mounts and pointed files as extrafilelogs.

OTEL Agent version is  0.76.0
AKS Version is 1.24.9

for now we are running one agent on single host only. we are looking to run multiple agents, how can we avoid duplicating logs</div>

**Comment by ramesh569** [comment]
Hi @atoulme, has this been in enhancement list ?

**Comment by omrozowicz-splunk** [comment]
This one is quite difficult as OTEL agents are not designed to listen to a file from a shared mount path, they're all daemonsets  that has access to its physical mount to forward logs to the destination.

In your case we'd need to have some kind of shared checkpoint so the agents won't send the same thing to splunk - but even if we'd have something like that, we'd use many agents to compete for the same file which is a waste of resources. It would make more sense to collect it from a single point (like in case of `clusterReceiver`, but this one does not have an access to filesystem). Ideally it'd come through an aks native one point of access, but I couldn't find anything like that/any receiver that does that.

I think that the way you use it currently is probably the best (to deploy only on one node to just send logs from this shared path), but I understand it might be tricky to use additional pair of agents only on chosen nodes. 

But, I might have missed something, @atoulme do you have any thoughts about this?

**Comment by atoulme** [comment]
Please consider opening a [Splunk Idea](https://ideas.splunk.com/) for this enhancement.
