### ISSUE TITLE
Outdated comment or helm chart

### ISSUE THREAD

**Issue by jrohitdev** [signalfx/splunk-otel-collector-chart#889]
### Describe the issue you're reporting

As part of upgrading helm chart it was observed that `disable_compression` is still `true`  even in the latest version (i.e `0.82.0`)

It is unclear if this was supposed to be enabled or if the comment is out-of-date.

https://github.com/signalfx/splunk-otel-collector-chart/blob/splunk-otel-collector-0.82.0/helm-charts/splunk-otel-collector/templates/config/_otel-collector.tpl#L116

**Comment by atoulme** [comment]
We're still going through this, we have a [PR](https://github.com/signalfx/splunk-otel-collector-chart/pull/601) open with some discussion. I will follow up on the PR.

**Comment by atoulme** [comment]
Please watch the PR for updates.
