### ISSUE TITLE
Issue with automatic upgrade of GKE Cluster

### ISSUE THREAD

**Issue by kumachop2** [signalfx/splunk-otel-collector-chart#897]
### Describe the issue you're reporting

Our Google Infra team had reported Splunk Agents v0.75.0 running in GKE clusters stopping the automatic upgrade part of GCP regular maintenance. Hence I have upgrade helm to v0.83.0, but still observing same issues. I have provided below the screens shots for your review. Please do advice on next steps.

Kubernetes version 1.24.14-gke.1200 

Node Version 1.24.13-gke.2500

![image](https://github.com/signalfx/splunk-otel-collector-chart/assets/107289628/f1345375-d3fa-4a7a-b577-13020db2d3a2)

![image](https://github.com/signalfx/splunk-otel-collector-chart/assets/107289628/7066e8d5-245d-45e6-b3ca-7de42aeb89da)

**Comment by jvoravong** [comment]
Update on Deprecated Endpoint Removal:
- A community contribution [fix](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/26516/files) is coming in release [v0.85.0](https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/tag/v0.85.0), it removed the scanning of deprecated autoscaling/v2beta2 and batch/v1beta1 endpoints. 

Additional Context:
- Impact: Clusters running Kubernetes v1.22 and below will no longer be able to collect metrics from these endpoints when using collector version v0.85.0 and above.
- Kubernetes Support: Core Kubernetes ceased active support for version 1.22 on August 28, 2022 ([source](https://endoflife.date/kubernetes)).
- EKS Support: Amazon EKS, known for a broader version support matrix, discontinued active support for version 1.22 on June 4, 2023 ([source](https://endoflife.date/amazon-eks)).

**Comment by jvoravong** [comment]
Fix release is out, see chart release [v0.85.0](https://github.com/signalfx/splunk-otel-collector-chart/releases/tag/splunk-otel-collector-0.85.0).
