### ISSUE TITLE
Running into issues while Enabling network explorer to collect network telemetry

### ISSUE THREAD

**Issue by kumachop2** [signalfx/splunk-otel-collector-chart#899]
Planning to enable network explorer to collect network telemetry. Encountering issues with accessing splunk-otel-network-explorer image (403) and able to access other five images. Please advice.

=====================================
quay.io/signalfx/splunk-otel-network-explorer:latest-v0.10
Error response from daemon: unauthorized: access to the requested resource is not authorized

![image](https://github.com/signalfx/splunk-otel-collector-chart/assets/107289628/855e3637-617f-44d5-9d00-62c04231caa4)

================================================
I'm able to access below listed images without any issues.

quay.io/signalfx/splunk-network-explorer-kernel-collector:latest-v0.10
quay.io/signalfx/splunk-network-explorer-cloud-collector:latest-v0.10
quay.io/signalfx/splunk-network-explorer-k8s-watcher:latest-v0.10
quay.io/signalfx/splunk-network-explorer-k8s-relay:latest-v0.10
quay.io/signalfx/splunk-network-explorer-reducer:latest-v0.10

Splunk Observability Cloud
Helm v0.83.0

**Comment by jvoravong** [comment]
A user only needs the 5 images in the last part of the previous message. quay.io/signalfx/splunk-otel-network-explorer does not exist.
