### ISSUE TITLE
Logs getting mixed from different containers/pods

### ISSUE THREAD

**Issue by kyaparla** [signalfx/splunk-otel-collector-chart#902]
### Describe the issue you're reporting

We noticed logs from different containers getting mixed and sent as one single event to splunk.  validated by logging to the k8s node and seeing the log file itself at /var/log.

In splunk,  mixed up logs are showing in 1 single line when doing view source.

Any idea why this would happen,  is it grouping logs different container based on multiline configs?  Appreciate if you can provide any pointers on how to troubleshoot to find whats causing this.

**Comment by omrozowicz-splunk** [comment]
Hey, 
Can you provide more details on version/environment/values.yaml that you use? I'd also appreciate screenshot/sample of an example of such situation (especially the sourcetype you mentioned), I've not seen something like this so far.
Do you have any additional config on top or this is OTel with the default settings?

**Comment by matthewmodestino** [comment]
Early versions of the `recombine` operator would cause this, but was fix a long while back adding:

source_identifier | $attributes["file.path"] | The field to separate one source of logs from others when combining them.
-- | -- | --

Would recommend you ensure you are not running a very old version of the chart, and that the `source_identifier` is used if you are customizing the log pipeline with your own recombine rules. 

source_identifier	$attributes["file.path"]	The [field](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/stanza/docs/types/field.md) to separate one source of logs from others when combining them.

**Comment by atoulme** [comment]
Closing as inactive. Please reopen if you have more questions.
