### ISSUE TITLE
Upgrade of GKE clusters has otel depreciated API - v1beta1/cronjobs and v2beta2/horizontalpodautoscalers

### ISSUE THREAD

**Issue by sakthi-sudhakar-partior** [signalfx/splunk-otel-collector-chart#918]
### Describe the issue you're reporting

Hi, 

For upgrading the GKE cluster from 1.24.14 to 1.26, the upgrade is blocked because of the depreciated API from OTEL.
The otel-collector helm has been patched to latest version 0.83.0 but still issue is there.

<img width="794" alt="image" src="https://github.com/signalfx/splunk-otel-collector-chart/assets/98447113/847d9edb-4924-4476-a6a4-f2a0121150ae">

<img width="803" alt="image" src="https://github.com/signalfx/splunk-otel-collector-chart/assets/98447113/61e696df-a702-41ed-b5e0-067e16010d68">

**Comment by jvoravong** [comment]
Update on Deprecated Endpoint Removal:
- A community contribution [fix](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/26516/files) is coming in release [v0.85.0](https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/tag/v0.85.0).

**Comment by sakthi-sudhakar-partior** [comment]
Can please confirm on the timeline for the new splunk otel release with the fix.

**Comment by jvoravong** [comment]
Fix release is out, see chart release [v0.85.0](https://github.com/signalfx/splunk-otel-collector-chart/releases/tag/splunk-otel-collector-0.85.0).
