### ISSUE TITLE
Adopt GDI specification v1.6.0

### ISSUE THREAD

**Issue by pellared** [signalfx/splunk-otel-collector-chart#925]
Adopt https://github.com/signalfx/gdi-specification/releases/tag/v1.6.0

**Comment by pellared** [comment]
> GDI repositories MUST adopt GDI specification changes by their next `MINOR` release
and within three months (whichever is sooner). The GDI specification and GDI
repositories MUST remove any deprecated specification at the next `MAJOR` release.

**Comment by rmfitzpatrick** [comment]
@pellared is there an issue or comment we can reference where you've provided actionable requests and demonstrations of items out of compliance with suggested adoption elements? tmk none of the current helm chart maintainers have contributed to the specification.

**Comment by atoulme** [comment]
I am closing this issue as we are following this work internally and will post compliance to the GDI specification through a PR. Please connect internally for any follow-ups.
