### ISSUE TITLE
Incorrect index error does not provide the name of the index

### ISSUE THREAD

**Issue by boriscosic** [signalfx/splunk-otel-collector-chart#935]
### Describe the issue you're reporting

Hi Splunk,

We run splunk otel collector agent on the EKS cluster with several hundred applications. Sometimes during a release we will see a higher number of logs drop related to team misspelling or using an incorrect index.

The error comes up in the agent as following with little indication to which indexes could be the issue.
```
https://xx.xx.xx.xx:8088/services/collector, response: {"text":"Incorrect index","code":7,"invalid-event-number":1}
2022-06-01 07:55:44 +0000 [debug]: #0 [Sending] Chunk: 5e05e370bc6ce510af94b857bc9dec51(13699581B).
2022-06-01 07:55:44 +0000 [error]: #0 Failed POST to https://xx.xx.xx.xx:8088/services/collector, response: {"text":"Incorrect index","code":7,"invalid-event-number":1}
```

We then need to reach out to our Splunk operations to help us determine the cause by querying the _internal index which provides the cause. This can be time consuming and disruptive to operations as incorrect_index causes the entire batch of logs from the node to be dropped until the index is resolved.

Can you include the index_name in this error for easier tracking and resolution?

Thanks

**Comment by atoulme** [comment]
Please consider also opening a Splunk idea: https://ideas.splunk.com/

**Comment by matthewmodestino** [comment]
@atoulme are you suggesting ideas so that Splunk team adds it to logging?

**Comment by omrozowicz-splunk** [comment]
I don't think Splunk's team will add it to the log message in the near future, they already give information of `invalid-event-number` which is not very useful in our case (as we don't know exactly the sequence of the batch). 

I think in this case enabling heartbeat on startup would make sense - this will try to send something at the Splunk HEC exporter startup and will log the message that something is wrong before we even try to send any data. This is the config that must be set to enable this feature: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/203014c9231e37520f78854dda56aed74cfb19a3/exporter/splunkhecexporter/README.md?plain=1#L65

**Comment by matthewmodestino** [comment]
Yeah, that's why I was asking what  the idea should actually ask for.

I am not sure we can implement anything on agent side, as the index can be dynamically set by the pipeline, and any batch can have multiple indexes in it (i believe).

**Comment by omrozowicz-splunk** [comment]
> Yeah, that's why I was asking what the idea should actually ask for.
> 
> I am not sure we can implement anything on agent side, as the index can be dynamically set by the pipeline, and any batch can have multiple indexes in it (i believe).

@matthewmodestino 
But heartbeat is something that already exists in Splunk HEC Exporter, and the only thing is to enable it in the config. For example, if I enable it with:

```
  splunk_hec/logs:
    token: "token"
    endpoint: "http://127.0.0.1:8088/services/collector"
    sourcetype: "something"
    index: "indexthatdoesnotexists"
    max_connections: 20
    disable_compression: false
    timeout: 50s
    heartbeat:
      startup: true
```

and index does not exist, I get the following message on the startup:

```
Error: cannot start pipelines: splunk_hec/logs: heartbeat on startup failed: Permanent error: "HTTP/1.1 400 Bad Request\r\nContent-Length: 60\r\nConnection: Keep-Alive\r\nContent-Type: application/json; charset=UTF-8\r\nDate: Mon, 02 Oct 2023 10:47:31 GMT\r\nServer: Splunkd\r\nVary: Authorization\r\nX-Content-Type-Options: nosniff\r\nX-Frame-Options: SAMEORIGIN\r\n\r\n{\"text\":\"Incorrect index\",\"code\":7,\"invalid-event-number\":1}"
```

and from the receiver that is written out in the log I can already figure out the index.

**Comment by matthewmodestino** [comment]
Right, but i assume that only applies to the default index. 

If the pipeline changes the index or we use annotations to route etc, that heartbeat wont identify the missing index.

@boriscosic did you open an idea? If not I can later today.

**Comment by omrozowicz-splunk** [comment]
> Right, but i assume that only applies to the default index.
> 
> If the pipeline changes the index or we use annotations to route etc, that heartbeat wont identify the missing index.
> 
> @boriscosic did you open an idea? If not I can later today.

ah, right, this is on the processor level already

**Comment by matthewmodestino** [comment]
Also searching _internal logs from splunk for httpinputdatahandler logs should be self service. Doesnt require calling splunk support...or shouldnt...

Regardless, would vastly simplify troubleshooting if the index was included. Will see what splunkd eng says.

**Comment by matthewmodestino** [comment]
Opened a Splunk idea here:

https://ideas.splunk.com/ideas/EID-I-2094

Please vote. I will socialize this internally.

**Comment by boriscosic** [comment]
Thanks @matthewmodestino I should've updated here. I have a similar idea going https://ideas.splunk.com/ideas/SFXIMMID-I-524 if we want to unify this topic.

**Comment by matthewmodestino** [comment]
No worries, i got you 😀 

Yeah lets go with the one I opened under Splunk Enterprise HEC as that is who is ultimately responsible for the return codes.

Throw the votes on the fire y'all!

**Comment by matthewmodestino** [comment]
@atoulme @omrozowicz-splunk fluentd (sck) allowed a "chunk key" that let you manage how batches are split up...

This may help guard against what we talked about here where an incorrect index impacts other events in the batch...

Does otel have something similar today in batch processor (will check)

https://docs.fluentd.org/configuration/buffer-section#chunk-keys

**Comment by matthewmodestino** [comment]
Ah! Batch already supports something like this..we just dont set it...not sure if it operates on the actual payload tho...

https://github.com/open-telemetry/opentelemetry-collector/tree/main/processor/batchprocessor


```
metadata_keys (default = empty): When set, this processor will create one batcher instance per distinct combination of values in the client.Metadata.
```

**Comment by atoulme** [comment]
You can batch grouped by a resource attribute, yes. https://github.com/open-telemetry/opentelemetry-collector/issues/4544

**Comment by matthewmodestino** [comment]
Not sure what exactly `client.metadata` is exactly...

**Comment by crazyoldmorrice** [comment]
> You can batch grouped by a resource attribute, yes. [open-telemetry/opentelemetry-collector#4544](https://github.com/open-telemetry/opentelemetry-collector/issues/4544)

Hi @atoulme , do you know if it’s possible to batch grouped by resource attribute when using the file log receiver please?
