### ISSUE TITLE
Port conflict, how do we specify different port

### ISSUE THREAD

**Issue by xxPhuNguyenxx** [signalfx/splunk-otel-collector-chart#939]
## Description
After running running helm and setting helm values as arguments using values.yaml file, we get error complaining about port already in use. how do we specify different port or resolve
helm install my-splunk-otel-collector --values my_values.yaml splunk-otel-collector-chart/splunk-otel-collector

## Steps to Reproduce
#1. Add Helm repo
helm repo add splunk-otel-collector-chart https://signalfx.github.io/splunk-otel-collector-chart
#2. set helm arguments using values yaml
helm install my-splunk-otel-collector --values my_values.yaml splunk-otel-collector-chart/splunk-otel-collector

## Expected Result
out of the box install to work

## Actual Result
getting the error
error otelcol/collector.go:247 Asynchronous error received, terminating process {"error": "listen tcp 0.0.0.0:8889: bind: address already in use"}[go.opentelemetry.io/collector](https://go.opentelemetry.io/collector)/otelcol.(*Collector).Run
[go.opentelemetry.io/collector@v0.85.0/otelcol/collector.go:247](https://go.opentelemetry.io/collector@v0.85.0/otelcol/collector.go:247)
[go.opentelemetry.io/collector/otelcol.NewCommand.func1](https://go.opentelemetry.io/collector/otelcol.NewCommand.func1)
[go.opentelemetry.io/collector@v0.85.0/otelcol/command.go:27](https://go.opentelemetry.io/collector@v0.85.0/otelcol/command.go:27)
[github.com/spf13](https://github.com/spf13)/cobra.(*Command).execute
[github.com/spf13/cobra@v1.7.0/command.go:940](https://github.com/spf13/cobra@v1.7.0/command.go:940)
[github.com/spf13](https://github.com/spf13)/cobra.(*Command).ExecuteC
[github.com/spf13/cobra@v1.7.0/command.go:1068](https://github.com/spf13/cobra@v1.7.0/command.go:1068)
[github.com/spf13](https://github.com/spf13)/cobra.(*Command).Execute
[github.com/spf13/cobra@v1.7.0/command.go:992](https://github.com/spf13/cobra@v1.7.0/command.go:992)
main.runInteractive
[github.com/signalfx/splunk-otel-collector/cmd/otelcol/main.go:100](https://github.com/signalfx/splunk-otel-collector/cmd/otelcol/main.go:100)
main.run
[github.com/signalfx/splunk-otel-collector/cmd/otelcol/main_others.go:26](https://github.com/signalfx/splunk-otel-collector/cmd/otelcol/main_others.go:26)
main.main
[github.com/signalfx/splunk-otel-collector/cmd/otelcol/main.go:93](https://github.com/signalfx/splunk-otel-collector/cmd/otelcol/main.go:93)
runtime.main
runtime/proc.go:250

### Chart version

0.85.0

## Environment
Cloud:EKS
k8s version: (e.g., 1.21.0)
OS: (e.g., "Ubuntu 20.04")

### Chart configuration
 clusterName: OCP-SBX-XXX
splunkPlatform:
  token: XXXXXXXX-YYYY-XXXX-XXXX-XXXXXXXXXXX
  endpoint: https://hecVIP:8088/services/collector/event/
  index: logindex
  metricsIndex: metricsindex
  insecureSkipVerify: true
  logsEnabled: true
  metricsEnabled: false
  tracesEnabled: false
  maxConnections: 10 # Maximum HTTP connections to use simultaneously when sending data.
  disableCompression: false # Whether to disable gzip compression over HTTP. Defaults to true.
  timeout: 10s # HTTP timeout when sending data. Defaults to 10s.
  idleConnTimeout: 5s # Idle connection timeout. defaults to 10s
  retryOnFailure:
    enabled: true
    initialInterval: 30s # Time to wait after the first failure before retrying; ignored if enabled is false. Defaults to 5s
    maxInterval: 60s # The upper bound on backoff; ignored if enabled is false. Default is 30s
    maxElapsedTime: 600s # The maximum amount of time spent trying to send a batch; ignored if enabled is false. Default is 300s
agent:
  config:
    processors:
      # Exclude all telemetry data (metrics, logs, traces) from a namespace named 'namespaceX'
      filter/exclude_all_telemetry_data_from_namespace:
        logs:
          exclude:
            match_type: regexp
            resource_attributes:
              - key: [k8s.namespace.name](http://k8s.namespace.name/)
                value: '^(datadog)$'
        metrics:
          exclude:
            match_type: regexp
            resource_attributes:
              - key: [k8s.namespace.name](http://k8s.namespace.name/)
                value: '^(datadog)$'
        traces:
          span:
            - 'attributes["[k8s.namespace.name](http://k8s.namespace.name/)"] != "datadog"'   
    # Define the data processing pipelines for logs, metrics, and traces
    service:
      pipelines:
        logs:
          processors:
            - filter/exclude_all_telemetry_data_from_namespace

logsEngine: otel
cloudProvider: "aws"
distribution: "openshift"
environment: sandbox

### Additional context

Wiley on the EKS is already using 8089, how do we change the configuration to use a different port.

**Comment by xxPhuNguyenxx** [comment]
not sure if this (https://docs.splunk.com/observability/en/gdi/opentelemetry/splunk-collector-troubleshooting.html) applies here, but we've tried adding the configuration into the yaml files as noted where we've tried replacing <new port> with 58889, but we  got the error "splunk-otel-collector: - service: Additional property telemetry is not allowed"

Add telemetry configuration under the service section:
service:
  telemetry:
    metrics:
      address: ":<new port>"

**Comment by omrozowicz-splunk** [comment]
Hey @xxPhuNguyenxx,
Can you provide your values.yaml? Or preferably agent's configmap (with anonymised Splunk's data of course). Based on that I think you'll need to overwrite that Prometheus config which is mentioned in the docs. If you don't use `gateway` I think it'd be enough to override it under `agent.config` like:

```
agent:
  config:
    receivers:
      prometheus/internal:
        config:
          scrape_configs:
          - job_name: 'otel-collector'
            scrape_interval: 10s
            static_configs:
            - targets: ['0.0.0.0:8889']
    service:
      telemetry:
        metrics:
          address: ":8889"
```
But change the port to something else.

**Comment by xxPhuNguyenxx** [comment]
Thanks this definitely worked.
