### ISSUE TITLE
Logs are missing during high loads

### ISSUE THREAD

**Issue by beth2016** [signalfx/splunk-otel-collector-chart#945]
## Description
When we run performance tests (40k requests/min) , we see logs are intermittently dropped for 30-90 seconds.   This issue started manifesting after we upgrade otel from 0.43 to 0.81.

### Chart version

0.81

## Environment
Cloud: Openshift
k8s version: 1.23

**Comment by matthewmodestino** [comment]
Hey Beth! Hope all is well!

This could be caused by file rotation under high load on the node, or other scenarios.

Any logs from the agents affected that may help?

**Comment by atoulme** [comment]
You might be best served by opening a support case to follow up. Please post the support case ID in this issue so we can work with you directly.
