### ISSUE TITLE
Enhancement: Add fluentd refresh_interval

### ISSUE THREAD

**Issue by InputObject2** [signalfx/splunk-otel-collector-chart#982]
In the splunk-connect-for-kubernetes chart, there is a value to configure the polling time for files (refresh_interval), with a default of 60 seconds.

We switched over to the splunk-otel-collector as recommended by the Splunk docs, but it looks like this value cannot be set in the current version of the chart.

In the [source.container.conf](https://github.com/signalfx/splunk-otel-collector-chart/blob/main/helm-charts/splunk-otel-collector/templates/configmap-fluentd.yaml#L73) (in the fluentd configmap), we'd need to add something liike:

```yaml
refresh_interval {{ .Values.fluentd.config.refreshInterval | default 60 }}
```

**Comment by atoulme** [comment]
Please open a Splunk idea at ideas.splunk.com and post it here.

**Comment by InputObject2** [comment]
Idea opened here: https://ideas.splunk.com/ideas/PORTALSID-I-192

**Comment by VihasMakwana** [comment]
@InputObject2 a PR is up for this. Will update you once it gets merged.

**Comment by InputObject2** [comment]
@atoulme this has been done for a while, the referenced PR was merged!

**Comment by atoulme** [comment]
Thanks!
