### ISSUE TITLE
Adding securityContext in splunk-otel-collector agent

### ISSUE THREAD

**Issue by ProboticsX** [signalfx/splunk-otel-collector-chart#995]
Hi,

I'm trying to add a few securityContext exceptions to the splunk-otel-collector agent and this is how my values.yaml file looks like:

![image](https://github.com/signalfx/splunk-otel-collector-chart/assets/36927669/cddde556-c256-4f86-a3c4-98782d3307c2)

Even after adding the lines above, the agent pods and DaemonSet still gives out the same error messages as they were giving out before adding the securityContext. 

The error messages looks like:

![image](https://github.com/signalfx/splunk-otel-collector-chart/assets/36927669/10d0fb9c-ed5d-4e11-abd4-096bf3a8c01a)

I'm a beginner and still learning, please let me know if anyone knows how to add securityContext and resolve these errors.
Thanks!

**Comment by sbylica-splunk** [comment]
Hi!

I tested it with a basic config on my machine and it seems to be working fine, could you send me entire values file for testing?

As an example, below is a fil that I used:

`
clusterName: "test_cluster"

splunkPlatform:
  endpoint: "https://x.x.x.x:8088/services/collector/event"
  token: "00000000-0000-0000-0000-000000000000"
  
  index: "main"
  insecureSkipVerify: true



agent:
  securityContext:
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
    capabilities:
      drop:
      - ALL
    runAsUser: 20000
    runAsGroup: 20000
`

Regards, Szymon

**Comment by atoulme** [comment]
We have not heard back ; please provide more information, if possible as a Splunk support request, so we can engage with you and help best. Closing as not planned.
